repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
        files: .*\.py
        exclude: (\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.pyc|__pycache__|_build|buck-out|build|dist|migrations\/.*\.py)
