runtime: python37
service: api
entrypoint: gunicorn -b :8080 -w 4 main:app
instance_class: F4

# inbound_services:
# - warmup

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
