runtime: python37
service: api
entrypoint: gunicorn -b :$PORT -w 4 main:app --timeout 90
instance_class: F4

# inbound_services:
# - warmup

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
