[tool.black]
line-length = 88
target-version = ['py37']
include = '.*\.py'
exclude = '(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.pyc|__pycache__|_build|buck-out|build|dist|migrations\/.*\.py)'