from app.common.xml_utils import StructureTypes, IdentityRoles

XML_PERRENOUD_CONFIGURATION = [
    {
        "id": 1,
        "is_root": True,
        "tag": "Projet",
    },
    {
        "id": 2,
        "tag": "Donnees_Techniques",
        "parent": "root",
    },
    {
        "id": 3,
        "tag": "Numero_Departement",
        "parent": 2,
        "has_value": True,
        "fields": ["id"],
        "rule": "get_department_number",
    },
    {
        "id": 4,
        "tag": "Lst001_Altitude_Liste",
        "parent": 2,
        "has_value": True,
        "fields": ["altitude"],
        "enum_index": 1,
    },
    {
        "id": 6,
        "tag": "Lst074_Type_Batiment",
        "parent": 2,
        "has_value": True,
        "fields": ["id"],
        "rule": "get_building_type",
    },
    {
        "id": 7,
        "tag": "Lst002_Annee_construction",
        "parent": 2,
        "has_value": True,
        "fields": ["id"],
        "rule": "get_construction_year",
    },
    {
        "id": 8,
        "tag": "Lst003_Etat",
        "parent": 2,
        "has_value": True,
        "fields": ["id"],
        "rule": "get_initial_state_status",
    },
    {
        "id": 9,
        "tag": "Batiment",
        "parent": "root",
    },
    {
        "id": 10,
        "tag": "Designation",
        "parent": 9,
        "has_value": True,
        "constant": " ",
    },
    {
        "id": 11,
        "tag": "Shab",
        "parent": 9,
        "has_value": True,
        "fields": ["id"],
        "rule": "get_living_area",
    },
    {
        "id": 12,
        "tag": "Lst004_Inertie",
        "parent": 9,
        "has_value": True,
        "fields": ["inertia"],
        "enum_index": 4,
    },
    {
        "id": 15,
        "tag": "Hsp",
        "parent": 9,
        "has_value": True,
        "fields": ["average_height_ceiling"],
    },
    {
        "id": 17,
        "tag": "Enveloppe",
        "parent": 9,
    },
    {
        "id": 18,
        "tag": "Murs_Collection",
        "parent": 17,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 19,
        "tag": "Mur",
        "parent": 18,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["walls"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 20,
        "tag": "Id",
        "parent": 19,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 21,
        "tag": "Designation",
        "parent": 19,
        "has_value": True,
        "fields": ["name"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 22,
        "tag": "Lst005_Position_Mur",
        "parent": 19,
        "has_value": True,
        "fields": ["wall_position"],
        "enum_index": 5,
    },
    {
        "id": 23,
        "tag": "Lst006_U_connu",
        "parent": 19,
        "has_value": True,
        "fields": ["known_U_value"],
    },
    {
        "id": 24,
        "tag": "Lst007_Composition_Mur",
        "parent": 19,
        "has_value": True,
        "fields": ["wall_composition"],
        "enum_index": 7,
        "validation": {
            "mandatory": True,
            "conditions": ["and", {"id": 22, "operator": "==", "value": 0}],
        },
    },
    {
        "id": 25,
        "tag": "Lst009_Paroi_Isolee",
        "parent": 19,
        "has_value": True,
        "fields": ["insulated_wall"],
    },
    {
        "id": 26,
        "tag": "Lst010_Type_Isolation",
        "parent": 19,
        "has_value": True,
        "fields": ["insulation_type"],
        "enum_index": 10,
        "validation": {
            "mandatory": True,
            "conditions": ["and", {"id": 25, "operator": "==", "value": 1}],
        },
    },
    {
        "id": 27,
        "tag": "Lst011_Composant_Lourd",
        "parent": 19,
        "has_value": True,
        "constant": 1,
    },
    {
        "id": 28,
        "tag": "Lst012_Valeur_Isolation",
        "parent": 19,
        "has_value": True,
        "fields": ["known_value"],
        "enum_index": 12,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 23, "operator": "==", "value": 0},
                {"id": 25, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 29,
        "tag": "R_Isolant",
        "parent": 19,
        "has_value": True,
        "fields": ["R_value"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 23, "operator": "==", "value": 0},
                {"id": 25, "operator": "==", "value": 1},
                {"id": 28, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 30,
        "tag": "Epaisseur_Isolant",
        "parent": 19,
        "has_value": True,
        "fields": ["insulation_thickness"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 23, "operator": "==", "value": 0},
                {"id": 25, "operator": "==", "value": 1},
                {"id": 28, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 32,
        "tag": "Lst011_Doublage_Brique",
        "parent": 19,
        "has_value": True,
        "fields": ["double_brick_with_air_gap"],
    },
    {
        "id": 33,
        "tag": "Lst011_Retour_Isolation",
        "parent": 19,
        "has_value": True,
        "fields": ["insulated_wall"],
        "rule": "get_insulation_return",
    },
    {
        "id": 35,
        "tag": "Calcul_b_Surface_Lnc_Ex",
        "parent": 19,
        "has_value": True,
        "constant": 100,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 22, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 36,
        "tag": "Calcul_b_Surface_Int_Lnc",
        "parent": 19,
        "has_value": True,
        "constant": 10,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 22, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 37,
        "tag": "Lst011_Calcul_b_Isol_Lnc_Ext",
        "parent": 19,
        "has_value": True,
        "fields": ["insulated_non_heated_exterior_wall"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 22, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 38,
        "tag": "Lst011_Calcul_b_Isol_Int_Lnc",
        "parent": 19,
        "has_value": True,
        "fields": ["insulated_heated_non_heated_wall"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 22, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 39,
        "tag": "Lst015_Calcul_b_Type_Local",
        "parent": 19,
        "has_value": True,
        "fields": ["local_type"],
        "enum_index": 15,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 22, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 40,
        "tag": "Valeur_U_Connu",
        "parent": 19,
        "has_value": True,
        "fields": ["known_U"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 22, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 41,
        "tag": "Planchers_Collection",
        "parent": 17,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 42,
        "tag": "Plancher",
        "parent": 41,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["floors"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 43,
        "tag": "Id",
        "parent": 42,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 44,
        "tag": "Designation",
        "parent": 42,
        "has_value": True,
        "fields": ["name"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 45,
        "tag": "Lst016_Position_Plancher",
        "parent": 42,
        "has_value": True,
        "fields": ["position"],
        "enum_index": 16,
    },
    {
        "id": 46,
        "tag": "Lst006_U_connu",
        "parent": 42,
        "has_value": True,
        "fields": ["known_U_value"],
    },
    {
        "id": 47,
        "tag": "Lst017_Composition_Plancher",
        "parent": 42,
        "has_value": True,
        "fields": ["main_component"],
        "enum_index": 17,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 46, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 48,
        "tag": "Lst009_Paroi_Isolee",
        "parent": 42,
        "has_value": True,
        "fields": ["insulated_wall"],
    },
    {
        "id": 49,
        "tag": "Lst018_Type_Isolation",
        "parent": 42,
        "has_value": True,
        "fields": ["insulation_type"],
        "enum_index": 18,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 48, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 50,
        "tag": "Lst012_Valeur_Isolation",
        "parent": 42,
        "has_value": True,
        "fields": ["known_insulation_value"],
        "enum_index": 12,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 46, "operator": "==", "value": 0},
                {"id": 48, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 51,
        "tag": "R_Isolant",
        "parent": 42,
        "has_value": True,
        "fields": ["R_value"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 46, "operator": "==", "value": 0},
                {"id": 48, "operator": "==", "value": 1},
                {"id": 50, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 52,
        "tag": "Epaisseur_Isolant",
        "parent": 42,
        "has_value": True,
        "fields": ["insulation_thickness"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 46, "operator": "==", "value": 0},
                {"id": 48, "operator": "==", "value": 1},
                {"id": 50, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 55,
        "tag": "Calcul_b_Surface_Lnc_Ex",
        "parent": 42,
        "has_value": True,
        "constant": 100,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 45, "operator": "==", "value": 2},
            ],
        },
    },
    {
        "id": 56,
        "tag": "Calcul_b_Surface_Int_Lnc",
        "parent": 42,
        "has_value": True,
        "constant": 10,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 45, "operator": "==", "value": 2},
            ],
        },
    },
    {
        "id": 57,
        "tag": "Lst011_Calcul_b_Isol_Lnc_Ext",
        "parent": 42,
        "has_value": True,
        "fields": ["insulated_non_heated_exterior_wall"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 45, "operator": "==", "value": 2},
            ],
        },
    },
    {
        "id": 58,
        "tag": "Lst011_Calcul_b_Isol_Int_Lnc",
        "parent": 42,
        "has_value": True,
        "fields": ["insulated_heated_non_heated_wall"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 45, "operator": "==", "value": 2},
            ],
        },
    },
    {
        "id": 59,
        "tag": "Lst015_Calcul_b_Type_Local",
        "parent": 42,
        "has_value": True,
        "fields": ["type_non_heated_local"],
        "enum_index": 15,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 45, "operator": "==", "value": 2},
            ],
        },
    },
    {
        "id": 60,
        "tag": "Lst011_Composant_Lourd",
        "parent": 42,
        "has_value": True,
        "constant": 1,
    },
    {
        "id": 61,
        "tag": "Valeur_U_Connu",
        "parent": 42,
        "has_value": True,
        "fields": ["U_value"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 46, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 62,
        "tag": "Plafonds_Collection",
        "parent": 17,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 63,
        "tag": "Plafond",
        "parent": 62,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["ceilings"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 64,
        "tag": "Id",
        "parent": 63,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 65,
        "tag": "Designation",
        "parent": 63,
        "has_value": True,
        "fields": ["name"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 66,
        "tag": "Lst019_Position_Plafond",
        "parent": 63,
        "has_value": True,
        "fields": ["ceiling_position"],
        "enum_index": 19,
    },
    {
        "id": 67,
        "tag": "Lst006_U_connu",
        "parent": 63,
        "has_value": True,
        "fields": ["known_U_value"],
    },
    {
        "id": 68,
        "tag": "Lst020_Composition_Plafond",
        "parent": 63,
        "has_value": True,
        "fields": ["composition"],
        "enum_index": 20,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 67, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 69,
        "tag": "Lst009_Paroi_Isolee",
        "parent": 63,
        "has_value": True,
        "fields": ["insulated_wall"],
    },
    {
        "id": 70,
        "tag": "Lst021_Type_Isolation",
        "parent": 63,
        "has_value": True,
        "fields": ["insulation_type"],
        "enum_index": 21,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 67, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 71,
        "tag": "Lst011_Composant_Lourd",
        "parent": 63,
        "has_value": True,
        "constant": "0",
    },
    {
        "id": 72,
        "tag": "Lst012_Valeur_Isolation",
        "parent": 63,
        "has_value": True,
        "fields": ["known_insulation_value"],
        "enum_index": 12,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 67, "operator": "==", "value": 0},
                {"id": 69, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 73,
        "tag": "R_Isolant",
        "parent": 63,
        "has_value": True,
        "fields": ["R_value"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 67, "operator": "==", "value": 0},
                {"id": 69, "operator": "==", "value": 1},
                {"id": 72, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 74,
        "tag": "Epaisseur_Isolant",
        "parent": 63,
        "has_value": True,
        "fields": ["insulation_thickness"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 67, "operator": "==", "value": 0},
                {"id": 69, "operator": "==", "value": 1},
                {"id": 72, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 77,
        "tag": "Calcul_b_Surface_Lnc_Ex",
        "parent": 63,
        "has_value": True,
        "constant": 100,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 66, "operator": "==", "value": 2},
            ],
        },
    },
    {
        "id": 78,
        "tag": "Calcul_b_Surface_Int_Lnc",
        "parent": 63,
        "has_value": True,
        "constant": 10,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 66, "operator": "==", "value": 2},
            ],
        },
    },
    {
        "id": 79,
        "tag": "Lst011_Calcul_b_Isol_Lnc_Ext",
        "parent": 63,
        "has_value": True,
        "fields": ["insulated_non_heated_exterior_wall"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 66, "operator": "==", "value": 2},
            ],
        },
    },
    {
        "id": 80,
        "tag": "Lst011_Calcul_b_Isol_Int_Lnc",
        "parent": 63,
        "has_value": True,
        "fields": ["insulated_heated_non_heated_wall"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 66, "operator": "==", "value": 2},
            ],
        },
    },
    {
        "id": 81,
        "tag": "Lst015_Calcul_b_Type_Local",
        "parent": 63,
        "has_value": True,
        "fields": ["type_non_heated_local"],
        "enum_index": 15,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 66, "operator": "==", "value": 2},
            ],
        },
    },
    {
        "id": 82,
        "tag": "Valeur_U_Connu",
        "parent": 63,
        "has_value": True,
        "fields": ["U_value"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 67, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 83,
        "tag": "Fenetres_Collection",
        "parent": 17,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 84,
        "tag": "Fenetre",
        "parent": 83,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["windows"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 85,
        "tag": "Id",
        "parent": 84,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 86,
        "tag": "Designation",
        "parent": 84,
        "has_value": True,
        "fields": ["windows_name"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 87,
        "tag": "Lst031_Type_Paroi_Vitree",
        "parent": 84,
        "has_value": True,
        "fields": ["glass_wall_type"],
        "enum_index": 31,
    },
    {
        "id": 88,
        "tag": "Lst006_U_connu",
        "parent": 84,
        "has_value": True,
        "fields": ["woodwork_known_U_value"],
    },
    {
        "id": 89,
        "tag": "Lst022_Type_Menuiserie",
        "parent": 84,
        "has_value": True,
        "fields": ["windows_type"],
        "enum_index": 22,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 87, "operator": "==", "value": 0},
                {"id": 88, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 90,
        "tag": "Lst023_Materiaux",
        "parent": 84,
        "has_value": True,
        "fields": ["materials"],
        "enum_index": 23,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 87, "operator": "==", "value": 0},
                {"id": 88, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 91,
        "tag": "Lst024_Vitrage",
        "parent": 84,
        "has_value": True,
        "fields": ["glass_type"],
        "enum_index": 24,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 87, "operator": "==", "value": 0},
                {"id": 88, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 92,
        "tag": "Lst025_Remplissage",
        "parent": 84,
        "has_value": True,
        "fields": ["argon_krypton_filling"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 87, "operator": "==", "value": 0},
                {"id": 88, "operator": "==", "value": 0},
                {"id": 91, "operator": ">", "value": 0},
            ],
        },
    },
    {
        "id": 93,
        "tag": "Lst026_Epaisseur_Lame",
        "parent": 84,
        "has_value": True,
        "fields": ["thickness_air_gap"],
        "enum_index": 26,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 87, "operator": "==", "value": 0},
                {"id": 88, "operator": "==", "value": 0},
                {"id": 91, "operator": ">", "value": 0},
            ],
        },
    },
    {
        "id": 94,
        "tag": "Lst027_Fermeture",
        "parent": 84,
        "has_value": True,
        "fields": ["closing_type"],
        "enum_index": 27,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 87, "operator": "==", "value": 0},
                {"id": 88, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 95,
        "tag": "Lst011_VIR",
        "parent": 84,
        "has_value": True,
        "fields": ["glass_insulated"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 87, "operator": "==", "value": 0},
                {"id": 88, "operator": "==", "value": 0},
                {"id": 91, "operator": ">", "value": 0},
            ],
        },
    },
    {
        "id": 96,
        "tag": "Lst011_Avec_Joint",
        "parent": 84,
        "has_value": True,
        "fields": ["id"],
        "rule": "has_seal",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 87, "operator": "==", "value": 0},
                {"id": 88, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 97,
        "tag": "Lst028_Largeur_Dormant",
        "parent": 84,
        "has_value": True,
        "constant": "0",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 87, "operator": "==", "value": 0},
                {"id": 88, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 98,
        "tag": "Lst029_Position",
        "parent": 84,
        "has_value": True,
        "constant": "2",
    },
    {
        "id": 99,
        "tag": "Lst030_Inclinaison",
        "parent": 84,
        "has_value": True,
        "fields": ["inclination"],
        "enum_index": 30,
    },
    {
        "id": 100,
        "tag": "Lst011_Presence_Double_Fenetre",
        "parent": 84,
        "has_value": True,
        "constant": "0",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 87, "operator": "==", "value": 0},
                {"id": 88, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 110,
        "tag": "Uw_Connu",
        "parent": 84,
        "has_value": True,
        "fields": ["woodwork_U_value"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 88, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 111,
        "tag": "CoefUjn_Connu",
        "parent": 84,
        "has_value": True,
        "fields": ["Ujn_value"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 88, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 112,
        "tag": "Portes_Collection",
        "parent": 17,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 113,
        "tag": "Porte",
        "parent": 112,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["doors"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 114,
        "tag": "Id",
        "parent": 113,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 115,
        "tag": "Designation",
        "parent": 113,
        "has_value": True,
        "fields": ["door_name"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 116,
        "tag": "Lst006_U_connu",
        "parent": 113,
        "has_value": True,
        "fields": ["door_known_U_value"],
    },
    {
        "id": 117,
        "tag": "Lst032_Nature_Menuiserie",
        "parent": 113,
        "has_value": True,
        "fields": ["door_nature"],
        "enum_index": 32,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 116, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 118,
        "tag": "Lst033_Type_Porte",
        "parent": 113,
        "has_value": True,
        "fields": ["door_type"],
        "enum_index": 33,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 116, "operator": "==", "value": 0},
                {"id": 117, "operator": "<", "value": 3},
            ],
        },
    },
    {
        "id": 119,
        "tag": "Lst029_Position",
        "parent": 113,
        "has_value": True,
        "constant": "2",
    },
    {
        "id": 120,
        "tag": "Lst028_Largeur_Dormant",
        "parent": 113,
        "has_value": True,
        "constant": "0",
    },
    {
        "id": 121,
        "tag": "Valeur_U_Connu",
        "parent": 113,
        "has_value": True,
        "fields": ["door_U_value"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 116, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 122,
        "tag": "Metre",
        "parent": 9,
    },
    {
        "id": 123,
        "tag": "Metre_Murs_Collection",
        "parent": 122,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 124,
        "tag": "Metre_Mur",
        "parent": 123,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["wall_inputs"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 125,
        "tag": "Id",
        "parent": 124,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 126,
        "tag": "Id_Enveloppe_Mur",
        "parent": 124,
        "identity_role": IdentityRoles.FOREIGN.value,
        "foreign_linked_entity": "wall",
        "fields": ["wall_id"],
    },
    {
        "id": 128,
        "tag": "Long_ou_Surface",
        "parent": 124,
        "has_value": True,
        "fields": ["surface"],
    },
    {
        "id": 129,
        "tag": "Largeur",
        "parent": 124,
        "has_value": True,
        "constant": "0",
    },
    {
        "id": 131,
        "tag": "Nombre_Vitrages",
        "parent": 124,
        "has_value": True,
        "fields": ["linked_areas_number_identicals"],
    },
    {
        "id": 132,
        "tag": "Surface_Vitrages",
        "parent": 124,
        "has_value": True,
        "fields": ["linked_areas_woodworks_surface"],
    },
    {
        "id": 133,
        "tag": "Metre_Vitrages_Portes_Collection",
        "parent": 124,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 134,
        "tag": "Metre_Vitrage_Porte",
        "parent": 133,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["linked_areas_woodworks"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 135,
        "tag": "Id",
        "parent": 134,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 136,
        "tag": "Id_Enveloppe_Vitrage",
        "parent": 134,
        "identity_role": IdentityRoles.FOREIGN.value,
        "foreign_linked_entity": "woodwork",
        "fields": ["woodwork_id"],
    },
    {
        "id": 137,
        "tag": "Nombre_Vitrage_Identique",
        "parent": 134,
        "has_value": True,
        "fields": ["number_identical_woodwork"],
    },
    {
        "id": 138,
        "tag": "Long_ou_Surface",
        "parent": 134,
        "has_value": True,
        "fields": ["total"],
    },
    {
        "id": 139,
        "tag": "Hauteur",
        "parent": 134,
        "has_value": True,
        "constant": "0",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 138, "operator": "!=", "value": 0},
            ],
        },
    },
    {
        "id": 140,
        "tag": "Perimetre",
        "parent": 134,
        "has_value": True,
        "fields": ["perimeter"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 139, "operator": "==", "value": 0},
            ],
        },
    },
    {"id": 141, "tag": "Lst011_Presence_Masques", "parent": 134, "constant": "0"},
    {
        "id": 156,
        "tag": "Metre_Plafonds_Collection",
        "parent": 122,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 157,
        "tag": "Metre_Plafond",
        "parent": 156,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["ceiling_inputs"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 158,
        "tag": "Id",
        "parent": 157,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 159,
        "tag": "Id_Enveloppe_Plafond",
        "parent": 157,
        "identity_role": IdentityRoles.FOREIGN.value,
        "foreign_linked_entity": "ceiling",
        "fields": ["ceiling_id"],
    },
    {
        "id": 161,
        "tag": "Long_ou_Surface",
        "parent": 157,
        "has_value": True,
        "fields": ["surface"],
    },
    {
        "id": 162,
        "tag": "Largeur",
        "parent": 157,
        "has_value": True,
        "constant": "0",
    },
    {
        "id": 164,
        "tag": "Nombre_Vitrages",
        "parent": 157,
        "has_value": True,
        "fields": ["linked_areas_number_identicals"],
    },
    {
        "id": 165,
        "tag": "Surface_Vitrages",
        "parent": 157,
        "has_value": True,
        "fields": ["linked_areas_woodworks_surface"],
    },
    {
        "id": 166,
        "tag": "Metre_Vitrages_Portes_Collection",
        "parent": 157,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 167,
        "tag": "Metre_Vitrage_Porte",
        "parent": 166,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["linked_areas_woodworks"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 168,
        "tag": "Id",
        "parent": 167,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 169,
        "tag": "Id_Enveloppe_Vitrage",
        "parent": 167,
        "identity_role": IdentityRoles.FOREIGN.value,
        "foreign_linked_entity": "woodwork",
        "fields": ["woodwork_id"],
    },
    {
        "id": 170,
        "tag": "Nombre_Vitrage_Identique",
        "parent": 167,
        "has_value": True,
        "fields": ["number_identical_woodwork"],
    },
    {
        "id": 171,
        "tag": "Long_ou_Surface",
        "parent": 167,
        "has_value": True,
        "fields": ["total"],
    },
    {
        "id": 172,
        "tag": "Hauteur",
        "parent": 167,
        "has_value": True,
        "constant": "0",
    },
    {
        "id": 173,
        "tag": "Perimetre",
        "parent": 167,
        "has_value": True,
        "fields": ["perimeter"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 172, "operator": "==", "value": 0},
            ],
        },
    },
    {"id": 174, "tag": "Lst011_Presence_Masques", "parent": 167, "constant": "0"},
    {
        "id": 189,
        "tag": "Metre_Planchers_Collection",
        "parent": 122,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 190,
        "tag": "Metre_Plancher",
        "parent": 189,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["floor_inputs"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 191,
        "tag": "Id",
        "parent": 190,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 192,
        "tag": "Id_Enveloppe_Plancher",
        "parent": 190,
        "identity_role": IdentityRoles.FOREIGN.value,
        "foreign_linked_entity": "floor",
        "fields": ["floor_id"],
    },
    {
        "id": 194,
        "tag": "Long_ou_Surface",
        "parent": 190,
        "has_value": True,
        "fields": ["surface"],
    },
    {"id": 195, "tag": "Largeur", "parent": 190, "has_value": True, "constant": "0"},
    {
        "id": 196,
        "tag": "Pth_ME_Plancher_Bas_Collection",
        "parent": 190,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 197,
        "tag": "Pth_ME_Plancher_Bas",
        "parent": 196,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["low_thermal_bridges"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 198,
        "tag": "Id",
        "parent": 197,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 199,
        "tag": "Longueur",
        "parent": 197,
        "has_value": True,
        "fields": ["length_m_liaison"],
    },
    {
        "id": 200,
        "tag": "Id_mur",
        "parent": 197,
        "has_value": True,
        "identity_role": IdentityRoles.FOREIGN.value,
        "foreign_linked_entity": "wall",
        "fields": ["wall_id"],
    },
    {
        "id": 201,
        "tag": "Id_Plancher_Bas",
        "parent": 197,
        "has_value": True,
        "identity_role": IdentityRoles.FOREIGN.value,
        "foreign_linked_entity": "floor",
        "fields": ["floor_id"],
    },
    {
        "id": 202,
        "tag": "Pth_ME_Plancher_Haut_Collection",
        "parent": 190,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 203,
        "tag": "Pth_ME_Plancher_Haut",
        "parent": 202,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["high_thermal_bridges"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 204,
        "tag": "Id",
        "parent": 203,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 205,
        "tag": "Longueur",
        "parent": 203,
        "has_value": True,
        "fields": ["length_m_liaison"],
    },
    {
        "id": 206,
        "tag": "Id_mur",
        "parent": 203,
        "has_value": True,
        "identity_role": IdentityRoles.FOREIGN.value,
        "foreign_linked_entity": "wall",
        "fields": ["wall_id"],
    },
    {
        "id": 207,
        "tag": "Id_Plancher_Haut",
        "parent": 203,
        "has_value": True,
        "identity_role": IdentityRoles.FOREIGN.value,
        "foreign_linked_entity": "floor",
        "fields": ["floor_id"],
    },
    {
        "id": 208,
        "tag": "Pth_ME_Plancher_Inter_Collection",
        "parent": 190,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 209,
        "tag": "Pth_ME_Plancher_Inter",
        "parent": 208,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["middle_thermal_bridges"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 210,
        "tag": "Id",
        "parent": 209,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 211,
        "tag": "Longueur",
        "parent": 209,
        "has_value": True,
        "fields": ["length_m_liaison"],
    },
    {
        "id": 212,
        "tag": "Id_mur",
        "parent": 209,
        "has_value": True,
        "identity_role": IdentityRoles.FOREIGN.value,
        "foreign_linked_entity": "wall",
        "fields": ["wall_id"],
    },
    {
        "id": 213,
        "tag": "Lst036_Position",
        "parent": 209,
        "has_value": True,
        "enum_index": 36,
        "fields": ["position_medium_floor"],
    },
    {"id": 214, "tag": "Pth_ME_Refend_Collection", "parent": 190},
    {
        "id": 215,
        "tag": "Pth_ME_Refend",
        "parent": 214,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["refend_thermal_bridges"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 216,
        "tag": "Id",
        "parent": 215,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 217,
        "tag": "Longueur",
        "parent": 215,
        "has_value": True,
        "fields": ["length_m_liaison"],
    },
    {
        "id": 218,
        "tag": "Id_mur",
        "parent": 215,
        "has_value": True,
        "identity_role": IdentityRoles.FOREIGN.value,
        "foreign_linked_entity": "wall",
        "fields": ["wall_id"],
    },
    {
        "id": 219,
        "tag": "Lst037_Position",
        "parent": 215,
        "has_value": True,
        "enum_index": 37,
        "fields": ["position_shear_wall"],
    },
    {
        "id": 220,
        "tag": "Generations_Collection",
        "parent": 9,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 221,
        "tag": "Generation",
        "parent": 220,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 222,
        "tag": "Id",
        "parent": 221,
        "has_value": True,
        "constant": "1",
    },
    {
        "id": 224,
        "tag": "Nombre_Generateur",
        "parent": 221,
        "has_value": True,
        "constant": "1",
    },
    {
        "id": 225,
        "tag": "Lst040_Gestion_Generateur",
        "parent": 221,
        "has_value": True,
        "constant": "0",
    },
    {
        "id": 226,
        "tag": "Lst011_Generation_en_Volume",
        "parent": 221,
        "has_value": True,
        "constant": "1",
    },
    {
        "id": 227,
        "tag": "Lst011_Existance_Systeme_Solaire",
        "parent": 221,
        "has_value": True,
        "constant": "0",
    },
    {
        "id": 230,
        "tag": "Generateurs_Collection",
        "parent": 221,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 231,
        "tag": "Generateur",
        "parent": 230,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["heatings"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 232,
        "tag": "Id",
        "parent": 231,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 234,
        "tag": "Lst038_Energie",
        "parent": 231,
        "has_value": True,
        "fields": "energy_used",
        "rule": "get_generator_energy",
    },
    {
        "id": 235,
        "tag": "Lst039_Type_Generateur",
        "parent": 231,
        "has_value": True,
        "fields": ["generator_type"],
        "enum_index": 39,
    },
    {
        "id": 236,
        "tag": "Puissance",
        "parent": 231,
        "has_value": True,
        "fields": ["power"],
        "rule": "get_power",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 235, "operator": ">=", "value": 101},
                {"id": 235, "operator": "<=", "value": 399},
            ],
        },
    },
    {
        "id": 237,
        "tag": "Nombre_Identique",
        "parent": 231,
        "has_value": True,
        "constant": "1",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 235, "operator": ">=", "value": 101},
                {"id": 235, "operator": "<=", "value": 399},
            ],
        },
    },
    {
        "id": 238,
        "tag": "Lst011_Caracteristiques_Connues",
        "parent": 231,
        "has_value": True,
        "fields": ["id"],
        "rule": "get_known_caracteristics",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 8, "operator": "==", "value": 1},
                [
                    "or",
                    [
                        "and",
                        {"id": 235, "operator": ">=", "value": 101},
                        {"id": 235, "operator": "<=", "value": 399},
                    ],
                    [
                        "and",
                        {"id": 235, "operator": ">=", "value": 501},
                        {"id": 235, "operator": "<=", "value": 599},
                    ],
                ],
            ],
        },
    },
    {
        "id": 240,
        "tag": "Rendement_Pn",
        "parent": 231,
        "has_value": True,
        "fields": ["full_yield"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 8, "operator": "==", "value": 1},
                {"id": 238, "operator": "==", "value": 1},
                {"id": 235, "operator": ">=", "value": 501},
                {"id": 235, "operator": "<=", "value": 599},
            ],
        },
    },
    {
        "id": 241,
        "tag": "Rendement_Pint",
        "parent": 231,
        "has_value": True,
        "fields": ["middle_yield"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 8, "operator": "==", "value": 1},
                {"id": 238, "operator": "==", "value": 1},
                {"id": 235, "operator": ">=", "value": 501},
                {"id": 235, "operator": "<=", "value": 599},
            ],
        },
    },
    {
        "id": 243,
        "tag": "Lst011_Presence_Regul",
        "parent": 231,
        "has_value": True,
        "fields": ["has_regulation"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "or",
                [
                    "and",
                    {"id": 235, "operator": ">=", "value": 101},
                    {"id": 235, "operator": "<=", "value": 499},
                ],
                [
                    "and",
                    {"id": 235, "operator": ">=", "value": 601},
                    {"id": 235, "operator": "<=", "value": 701},
                ],
            ],
        },
    },
    {
        "id": 245,
        "tag": "COP",
        "parent": 231,
        "has_value": True,
        "fields": ["COP"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 8, "operator": "==", "value": 1},
                {"id": 238, "operator": "==", "value": 1},
                {"id": 235, "operator": ">=", "value": 501},
                {"id": 235, "operator": "<=", "value": 599},
            ],
        },
    },
    {
        "id": 246,
        "tag": "Lst011_Chaudiere_Murale",
        "parent": 231,
        "has_value": True,
        "fields": ["wall_mounted_boiler"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 235, "operator": ">=", "value": 101},
                {"id": 235, "operator": "<=", "value": 299},
            ],
        },
    },
    {
        "id": 247,
        "tag": "Lst011_Presence_Veilleuse",
        "parent": 231,
        "has_value": True,
        "constant": "0",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 235, "operator": ">=", "value": 201},
                {"id": 235, "operator": "<=", "value": 299},
            ],
        },
    },
    {
        "id": 248,
        "tag": "Lst011_COP_Certifie",
        "parent": 231,
        "has_value": True,
        "constant": "1",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 8, "operator": "==", "value": 1},
                {"id": 238, "operator": "==", "value": 1},
                {"id": 235, "operator": ">=", "value": 501},
                {"id": 235, "operator": "<=", "value": 599},
            ],
        },
    },
    {
        "id": 250,
        "tag": "Emissions_Collection",
        "parent": 9,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 251,
        "tag": "Emission",
        "parent": 250,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["heatings"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 252,
        "tag": "Id",
        "parent": 251,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 253,
        "tag": "Designation",
        "parent": 251,
        "has_value": True,
        "fields": ["heating_name"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 254,
        "tag": "Surface_Concernee",
        "parent": 251,
        "has_value": True,
        "fields": ["heated_area"],
    },
    {
        "id": 255,
        "tag": "Lst041_Type_Emission",
        "parent": 251,
        "has_value": True,
        "fields": ["emissions_type"],
        "enum_index": 41,
    },
    {
        "id": 256,
        "tag": "Lst042_Type_Chauffage",
        "parent": 251,
        "has_value": True,
        "fields": ["energy_used"],
        "enum_index": 42,
    },
    {
        "id": 257,
        "tag": "Lst043_Type_Emetteur",
        "parent": 251,
        "has_value": True,
        "fields": ["emettor_type"],
        "enum_index": 43,
    },
    {
        "id": 258,
        "tag": "Lst011_Regul_Piece",
        "parent": 251,
        "has_value": True,
        "fields": ["emettor_type"],
        "rule": "get_regulation_by_room",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 255, "operator": ">", "value": 0},
            ],
        },
    },
    {
        "id": 259,
        "tag": "Lst044_Equip_Intermittence",
        "parent": 251,
        "has_value": True,
        "fields": ["intermittent_equipment"],
        "enum_index": 44,
    },
    {
        "id": 260,
        "tag": "Lst045_Type_Reseau",
        "parent": 251,
        "has_value": True,
        "fields": ["intermittent_equipment"],
        "rule": "get_network_type",
    },
    {
        "id": 261,
        "tag": "Lst011_Reseau_Isole",
        "parent": 251,
        "has_value": True,
        "fields": ["isolated_network"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 255, "operator": ">", "value": 0},
                {"id": 260, "operator": ">", "value": 0},
            ],
        },
    },
    {
        "id": 262,
        "tag": "Generation_Liee",
        "parent": 251,
        "has_value": True,
        "constant": "1",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 255, "operator": ">", "value": 0},
            ],
        },
    },
    {
        "id": 263,
        "tag": "Lst011_Emet_Relie_Tarif_Collectif",
        "parent": 251,
        "has_value": True,
        "constant": "0",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 255, "operator": "==", "value": 0},
                {"id": 256, "operator": "==", "value": 5},
                {"id": 6, "operator": ">", "value": 1},
            ],
        },
    },
    {
        "id": 264,
        "tag": "Lst011_Presence_Appoint_Bois",
        "parent": 251,
        "has_value": True,
        "fields": ["wood_oven"],
    },
    {
        "id": 265,
        "tag": "Lst046_Type_Poele",
        "parent": 251,
        "has_value": True,
        "fields": ["equipment_performance"],
        "enum_index": 46,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 264, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 266,
        "tag": "Lst011_Instal_Base_Et_Appoint",
        "parent": 251,
        "has_value": True,
        "constant": "0",
    },
    {
        "id": 267,
        "tag": "Lst047_Annee_Emetteur",
        "parent": 251,
        "has_value": True,
        "fields": ["installation_year"],
        "enum_index": 47,
        "validation": {
            "mandatory": True,
            "conditions": [
                "or",
                [
                    "and",
                    {"id": 257, "operator": ">=", "value": 301},
                    {"id": 257, "operator": "<=", "value": 308},
                ],
                [
                    "and",
                    {"id": 257, "operator": ">=", "value": 401},
                    {"id": 257, "operator": "<=", "value": 408},
                ],
                [
                    "and",
                    {"id": 257, "operator": ">=", "value": 501},
                    {"id": 257, "operator": "<=", "value": 508},
                ],
                [
                    "and",
                    {"id": 257, "operator": ">=", "value": 601},
                    {"id": 257, "operator": "<=", "value": 608},
                ],
            ],
        },
    },
    {
        "id": 269,
        "tag": "Ecs_Collection",
        "parent": 9,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 270,
        "tag": "Ecs_Collection",
        "parent": 269,
        "structure_type": StructureTypes.ITERATION.value,
        "fields": ["hot_waters"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 271,
        "tag": "Id",
        "parent": 251,
        "identity_role": IdentityRoles.PRIMARY.value,
    },
    {
        "id": 272,
        "tag": "Designation",
        "parent": 270,
        "has_value": True,
        "fields": ["name"],
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 273,
        "tag": "Lst048_Type_ECS",
        "parent": 270,
        "has_value": True,
        "fields": ["type"],
        "enum_index": 48,
    },
    {
        "id": 274,
        "tag": "Lst049_Installation",
        "parent": 270,
        "has_value": True,
        "constant": "0",
    },
    {
        "id": 275,
        "tag": "Lst050_Position",
        "parent": 270,
        "has_value": True,
        "fields": ["production_living_volume"],
        "enum_index": 50,
    },
    {
        "id": 276,
        "tag": "Lst011_Pieces_Contigues",
        "parent": 270,
        "has_value": True,
        "fields": ["linked_rooms"],
    },
    {
        "id": 277,
        "tag": "Lst051_Instant_Accu",
        "parent": 270,
        "has_value": True,
        "fields": ["production_type"],
        "enum_index": 51,
    },
    {
        "id": 278,
        "tag": "Lst052_Type_CE",
        "parent": 270,
        "has_value": True,
        "fields": ["boiler_type"],
        "enum_index": 52,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 273, "operator": "==", "value": 101},
            ],
        },
    },
    {
        "id": 279,
        "tag": "Lst053_Type_CET",
        "parent": 270,
        "has_value": True,
        "constant": "0",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 273, "operator": "==", "value": 102},
            ],
        },
    },
    {
        "id": 280,
        "tag": "Lst011_CET_Presence_Appoint",
        "parent": 270,
        "has_value": True,
        "constant": "0",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 273, "operator": "==", "value": 102},
            ],
        },
    },
    {
        "id": 281,
        "tag": "Lst054_CET_Alimentation",
        "parent": 270,
        "has_value": True,
        "constant": "1",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 273, "operator": "==", "value": 102},
            ],
        },
    },
    {
        "id": 282,
        "tag": "Generation_Liee",
        "parent": 270,
        "has_value": True,
        "constant": "1",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 273, "operator": "==", "value": 201},
            ],
        },
    },
    {
        "id": 283,
        "tag": "Generation_Liee",
        "parent": 270,
        "has_value": True,
        "constant": "1",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 273, "operator": "==", "value": 201},
            ],
        },
    },
    {
        "id": 285,
        "tag": "Lst011_ECS_Renovee",
        "parent": 270,
        "has_value": True,
        "fields": ["renovated_production"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 8, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 288,
        "tag": "Lst011_Presence_Veilleuse",
        "parent": 270,
        "has_value": True,
        "fields": ["has_light"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 273, "operator": ">=", "value": 202},
                {"id": 273, "operator": "<=", "value": 204},
            ],
        },
    },
    {
        "id": 290,
        "tag": "Lst057_Type_Accumulateur",
        "parent": 270,
        "has_value": True,
        "constant": "0",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 273, "operator": "==", "value": 203},
            ],
        },
    },
    {
        "id": 291,
        "tag": "Lst058_Annee_Accumulateur_Classique",
        "parent": 270,
        "has_value": True,
        "fields": ["year_classic_accumulator"],
        "enum_index": 58,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 290, "operator": "==", "value": 0},
                {"id": 273, "operator": "==", "value": 203},
            ],
        },
    },
    {
        "id": 294,
        "tag": "Lst011_Presence_Solaire",
        "parent": 270,
        "has_value": True,
        "fields": ["existing_solar_device"],
    },
    {
        "id": 295,
        "tag": "Lst060_Type_Solaire",
        "parent": 270,
        "has_value": True,
        "fields": ["solar_device_type"],
        "enum_index": 60,
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 294, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 296,
        "tag": "Lst011_Fecs_Inconnu",
        "parent": 270,
        "constant": "1",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 294, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 298,
        "tag": "Lst011_Instal_Moins_5_ans",
        "parent": 270,
        "constant": "1",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 294, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 299,
        "tag": "Volume_Ballon",
        "parent": 270,
        "has_value": True,
        "fields": ["water_tank_volume"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 277, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 300,
        "tag": "Nombre_Identique",
        "parent": 270,
        "constant": "1",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 277, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 303,
        "tag": "Divers",
        "parent": 9,
        "validation": {
            "mandatory": False,
        },
    },
    {
        "id": 304,
        "tag": "Lst062_Type_Ventilation",
        "parent": 303,
        "has_value": True,
        "fields": ["airflow_device"],
        "enum_index": 62,
    },
    {
        "id": 305,
        "tag": "Lst011_Presence_Cheminee_Trappe",
        "parent": 303,
        "has_value": True,
        "constant": "0",
    },
    {
        "id": 306,
        "tag": "Lst063_Climatisation",
        "parent": 303,
        "has_value": True,
        "fields": ["air_conditioning_type"],
        "enum_index": 63,
    },
    {
        "id": 307,
        "tag": "Surface_Climatisee",
        "parent": 303,
        "has_value": True,
        "fields": ["total_air_conditioned_area"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 306, "operator": ">", "value": 0},
                {"id": 6, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 308,
        "tag": "Collectif_Surface_Clim_Etage_Courant",
        "parent": 303,
        "has_value": True,
        "fields": ["total_air_conditioned_area"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 306, "operator": ">", "value": 0},
                {"id": 6, "operator": ">", "value": 1},
            ],
        },
    },
    {
        "id": 309,
        "tag": "Collectif_Surface_Clim_Dernier_Etage",
        "parent": 303,
        "has_value": True,
        "constant": "0",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 306, "operator": ">", "value": 0},
                {"id": 6, "operator": ">", "value": 1},
            ],
        },
    },
    {
        "id": 310,
        "tag": "Lst066_Tarif_Clim",
        "parent": 303,
        "has_value": True,
        "constant": "0",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 306, "operator": ">", "value": 0},
                {"id": 6, "operator": ">", "value": 1},
            ],
        },
    },
    {
        "id": 311,
        "tag": "Lst064_MI_Abon_Gaz",
        "parent": 303,
        "has_value": True,
        "fields": "id",
        "rule": "has_gaz_heating",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 6, "operator": ">", "value": 3},
            ],
        },
    },
    {
        "id": 315,
        "tag": "Lst011_Presence_Pv",
        "parent": 303,
        "has_value": True,
        "fields": ["has_photovoltaic_device"],
    },
    {
        "id": 316,
        "tag": "Lst011_Prod_Pv_Connue",
        "parent": 303,
        "has_value": True,
        "constant": "0",
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 315, "operator": "==", "value": 1},
            ],
        },
    },
    {
        "id": 317,
        "tag": "Surface_Capteurs",
        "parent": 303,
        "has_value": True,
        "fields": ["photovoltaic_device_surface"],
        "validation": {
            "mandatory": True,
            "conditions": [
                "and",
                {"id": 315, "operator": "==", "value": 1},
                {"id": 316, "operator": "==", "value": 0},
            ],
        },
    },
    {
        "id": 319,
        "tag": "Lst011_Presence_Eol",
        "parent": 303,
        "has_value": True,
        "constant": "0",
    },
]
