"""simulation table draft

Revision ID: d6dec70f738f
Revises: 217ddec57f4e
Create Date: 2020-05-26 17:48:11.549422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6dec70f738f"
down_revision = "217ddec57f4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation")),
        schema="core",
    )
    op.create_table(
        "simulation_use_case",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("use_case_name", sa.String(length=255), nullable=False),
        sa.Column("simulation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["core.simulation.id"],
            name=op.f("fk_simulation_use_case_simulation_id_simulation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_use_case")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("simulation_use_case", schema="core")
    op.drop_table("simulation", schema="core")
    # ### end Alembic commands ###
