"""Unique Antenna name

Revision ID: 18e21647a250
Revises: e2e96d918b5b
Create Date: 2020-04-22 07:54:31.488314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "18e21647a250"
down_revision = "e2e96d918b5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_antenna_name"), "antenna", ["name"], schema="core"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_antenna_name"), "antenna", schema="core", type_="unique"
    )
    # ### end Alembic commands ###
