"""quote_simulation

Revision ID: 58c83a42ab07
Revises: d6dec70f738f
Create Date: 2020-05-27 14:09:58.981390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58c83a42ab07"
down_revision = "d6dec70f738f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quote_simulation",
        sa.Column("quote_id", sa.Integer(), nullable=True),
        sa.Column("simulation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["core.quote.id"],
            name=op.f("fk_quote_simulation_quote_id_quote"),
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["core.simulation.id"],
            name=op.f("fk_quote_simulation_simulation_id_simulation"),
        ),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quote_simulation", schema="core")
    # ### end Alembic commands ###
