"""link simulations to projects

Revision ID: 00e8fbb91c13
Revises: 139a7170dbad
Create Date: 2020-06-16 10:17:35.252615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00e8fbb91c13"
down_revision = "139a7170dbad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulation",
        sa.Column("project_id", sa.Integer(), nullable=True),
        schema="core",
    )
    op.create_foreign_key(
        op.f("fk_simulation_project_id_project"),
        "simulation",
        "project",
        ["project_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_simulation_project_id_project"),
        "simulation",
        schema="core",
        type_="foreignkey",
    )
    op.drop_column("simulation", "project_id", schema="core")
    # ### end Alembic commands ###
