"""search model

Revision ID: a0eb8c693b7a
Revises: 18e21647a250
Create Date: 2020-04-22 18:27:10.159370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a0eb8c693b7a"
down_revision = "18e21647a250"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("search", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search", schema="core")
    # ### end Alembic commands ###
