"""add modification dates into simulation_quote

Revision ID: e5e96c61e90e
Revises: 2714523a7b14
Create Date: 2020-06-09 15:48:38.963204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e5e96c61e90e"
down_revision = "2714523a7b14"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulation_quote",
        sa.Column("modification_date", sa.Date(), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulation_quote", "modification_date", schema="core")
    # ### end Alembic commands ###
