"""Add missing status dates

Revision ID: 66e6fad5485d
Revises: 1e3b31caadbe
Create Date: 2020-05-25 10:57:46.237837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "66e6fad5485d"
down_revision = "1e3b31caadbe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("date_asking_for_pay", sa.Date(), nullable=True),
        schema="core",
    )
    op.add_column(
        "project",
        sa.Column("date_build_on_going", sa.Date(), nullable=True),
        schema="core",
    )
    op.add_column(
        "project", sa.Column("date_certified", sa.Date(), nullable=True), schema="core"
    )
    op.add_column(
        "project", sa.Column("date_cleared", sa.Date(), nullable=True), schema="core"
    )
    op.add_column(
        "project", sa.Column("date_contact", sa.Date(), nullable=True), schema="core"
    )
    op.add_column(
        "project", sa.Column("date_depositted", sa.Date(), nullable=True), schema="core"
    )
    op.add_column(
        "project", sa.Column("date_dismissed", sa.Date(), nullable=True), schema="core"
    )
    op.add_column(
        "project",
        sa.Column("date_meet_advices_planned", sa.Date(), nullable=True),
        schema="core",
    )
    op.add_column(
        "project",
        sa.Column("date_meet_control_planned", sa.Date(), nullable=True),
        schema="core",
    )
    op.add_column(
        "project",
        sa.Column("date_meet_to_process", sa.Date(), nullable=True),
        schema="core",
    )
    op.add_column(
        "project",
        sa.Column("date_non_eligible", sa.Date(), nullable=True),
        schema="core",
    )
    op.add_column(
        "project",
        sa.Column("date_payment_request_to_do", sa.Date(), nullable=True),
        schema="core",
    )
    op.add_column(
        "project", sa.Column("date_to_contact", sa.Date(), nullable=True), schema="core"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "date_to_contact", schema="core")
    op.drop_column("project", "date_payment_request_to_do", schema="core")
    op.drop_column("project", "date_non_eligible", schema="core")
    op.drop_column("project", "date_meet_to_process", schema="core")
    op.drop_column("project", "date_meet_control_planned", schema="core")
    op.drop_column("project", "date_meet_advices_planned", schema="core")
    op.drop_column("project", "date_dismissed", schema="core")
    op.drop_column("project", "date_depositted", schema="core")
    op.drop_column("project", "date_contact", schema="core")
    op.drop_column("project", "date_cleared", schema="core")
    op.drop_column("project", "date_certified", schema="core")
    op.drop_column("project", "date_build_on_going", schema="core")
    op.drop_column("project", "date_asking_for_pay", schema="core")
    # ### end Alembic commands ###
