"""simulations_uses_models

Revision ID: 1c89df0bd4d9
Revises: 26d0a23f8160
Create Date: 2020-06-19 11:10:21.324874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1c89df0bd4d9"
down_revision = "26d0a23f8160"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_certified",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("certification_date", sa.Date(), nullable=True),
        sa.Column("funder_id", sa.Integer(), nullable=True),
        sa.Column("simulation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["funder_id"],
            ["core.funder.id"],
            name=op.f("fk_simulation_certified_funder_id_funder"),
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["core.simulation.id"],
            name=op.f("fk_simulation_certified_simulation_id_simulation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_certified")),
        schema="core",
    )
    op.create_table(
        "simulation_deposit",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("deposit_date", sa.Date(), nullable=True),
        sa.Column("funder_id", sa.Integer(), nullable=True),
        sa.Column("simulation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["funder_id"],
            ["core.funder.id"],
            name=op.f("fk_simulation_deposit_funder_id_funder"),
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["core.simulation.id"],
            name=op.f("fk_simulation_deposit_simulation_id_simulation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_deposit")),
        schema="core",
    )
    op.create_table(
        "simulation_payment_request",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("payment_request_date", sa.Date(), nullable=True),
        sa.Column("funder_id", sa.Integer(), nullable=True),
        sa.Column("simulation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["funder_id"],
            ["core.funder.id"],
            name=op.f("fk_simulation_payment_request_funder_id_funder"),
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["core.simulation.id"],
            name=op.f("fk_simulation_payment_request_simulation_id_simulation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_payment_request")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("simulation_payment_request", schema="core")
    op.drop_table("simulation_deposit", schema="core")
    op.drop_table("simulation_certified", schema="core")
    # ### end Alembic commands ###
