"""Add Google Group Id

Revision ID: cdf376d513be
Revises: 0db0bc1782ad
Create Date: 2020-06-10 14:48:34.770056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cdf376d513be"
down_revision = "0db0bc1782ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mission",
        sa.Column("google_group_id", sa.String(length=255), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mission", "google_group_id", schema="core")
    # ### end Alembic commands ###
