"""fix date quotes to datetime

Revision ID: 7c034e3842cf
Revises: e5e96c61e90e
Create Date: 2020-06-10 13:49:50.017261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7c034e3842cf"
down_revision = "e5e96c61e90e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "simulation_quote",
        "modification_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "simulation_quote",
        "modification_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema="core",
    )
    # ### end Alembic commands ###
