"""add two status dates

Revision ID: 938ed27829b8
Revises: 1b7fb2899b9d
Create Date: 2020-05-14 17:35:36.000397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "938ed27829b8"
down_revision = "1b7fb2899b9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("date_meet_advices_to_plan", sa.Date(), nullable=True),
        schema="core",
    )
    op.add_column(
        "project",
        sa.Column("date_meet_control_to_plan", sa.Date(), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "date_meet_control_to_plan", schema="core")
    op.drop_column("project", "date_meet_advices_to_plan", schema="core")
    # ### end Alembic commands ###
