"""accomodation model

Revision ID: 5e81085eced8
Revises: 95a12d6d99e0
Create Date: 2020-04-16 16:23:18.276205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e81085eced8"
down_revision = "55e4a31e1790"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accomodation",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("accommodation_type", sa.String(length=255), nullable=True),
        sa.Column("condominium", sa.Boolean(), nullable=True),
        sa.Column("purchase_year", sa.Date(), nullable=True),
        sa.Column("construction_year", sa.Date(), nullable=True),
        sa.Column("levels_nb", sa.Integer(), nullable=True),
        sa.Column("rooms_nb", sa.Integer(), nullable=True),
        sa.Column("living_area", sa.Float(), nullable=True),
        sa.Column("additional_area", sa.Float(), nullable=True),
        sa.Column("vacant", sa.Boolean(), nullable=True),
        sa.Column("year_nb", sa.Date(), nullable=True),
        sa.Column("commentary", sa.String(length=800), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accomodation")),
        schema="core",
    )
    op.create_table(
        "disorder",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("localisation", sa.String(length=255), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("analysis_type", sa.String(length=255), nullable=True),
        sa.Column("analysis_comment", sa.String(length=2083), nullable=True),
        sa.Column("recommendation_type", sa.String(length=255), nullable=True),
        sa.Column("recommendation_comment", sa.String(length=2083), nullable=True),
        sa.Column("accomodation_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["accomodation_id"],
            ["core.accomodation.id"],
            name=op.f("fk_disorder_accomodation_id_accomodation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disorder")),
        schema="core",
    )
    op.add_column(
        "project",
        sa.Column("accomodation_id", sa.Integer(), nullable=True),
        schema="core",
    )
    op.create_unique_constraint(
        op.f("uq_project_accomodation_id"),
        "project",
        ["accomodation_id"],
        schema="core",
    )
    op.create_foreign_key(
        op.f("fk_project_accomodation_id_accomodation"),
        "project",
        "accomodation",
        ["accomodation_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_project_accomodation_id_accomodation"),
        "project",
        schema="core",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("uq_project_accomodation_id"), "project", schema="core", type_="unique"
    )
    op.drop_column("project", "accomodation_id", schema="core")
    op.drop_table("disorder", schema="core")
    op.drop_table("accomodation", schema="core")
    # ### end Alembic commands ###
