"""client deactivation

Revision ID: 01ccb957938f
Revises: 2ccc8e5a2201
Create Date: 2020-05-13 14:33:54.858416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "01ccb957938f"
down_revision = "1be295f0450a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client", sa.Column("active", sa.Boolean(), nullable=True), schema="core"
    )
    op.alter_column(
        "project",
        "type",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "type",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
        schema="core",
    )
    op.drop_column("client", "active", schema="core")
    # ### end Alembic commands ###
