"""project_supervisors

Revision ID: f8d81ff5a3c8
Revises: 16e3807f7b28
Create Date: 2020-04-15 17:09:06.356516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f8d81ff5a3c8"
down_revision = "16e3807f7b28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supervisor",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["core.project.id"],
            name=op.f("fk_supervisor_project_id_project"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["core.user.id"], name=op.f("fk_supervisor_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supervisor")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("supervisor", schema="core")
    # ### end Alembic commands ###
