"""relation_accommodations_project

Revision ID: 7ac45bcf6146
Revises: 8231ff267283
Create Date: 2020-06-30 13:02:04.166574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ac45bcf6146"
down_revision = "8231ff267283"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accommodation",
        sa.Column("project_id", sa.Integer(), nullable=True),
        schema="core",
    )
    op.create_foreign_key(
        op.f("fk_accommodation_project_id_project"),
        "accommodation",
        "project",
        ["project_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_accommodation_project_id_project"),
        "accommodation",
        schema="core",
        type_="foreignkey",
    )
    op.drop_column("accommodation", "project_id", schema="core")
    # ### end Alembic commands ###
