"""add projects models

Revision ID: 403a79d79190
Revises: 879c4cd0883e
Create Date: 2020-04-10 08:12:53.488353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "403a79d79190"
down_revision = "879c4cd0883e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requester",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=10), nullable=True),
        sa.Column("birthday_date", sa.Date(), nullable=True),
        sa.Column("phone_number_1", sa.String(length=255), nullable=False),
        sa.Column("phone_number_2", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("date_contact", sa.Date(), nullable=True),
        sa.Column("contact_source", sa.String(length=255), nullable=True),
        sa.Column("minors_occupants_number", sa.Integer(), nullable=True),
        sa.Column("adults_occupants_number", sa.Integer(), nullable=True),
        sa.Column("profession", sa.String(length=255), nullable=True),
        sa.Column("resources_category", sa.String(length=255), nullable=True),
        sa.Column("non_eligible", sa.Boolean(), nullable=True),
        sa.Column("ineligibility", sa.String(length=255), nullable=True),
        sa.Column("PTZ_year", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requester")),
        schema="core",
    )
    op.create_table(
        "contact",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("main_contact", sa.Boolean(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=10), nullable=True),
        sa.Column("phone_number", sa.String(length=255), nullable=False),
        sa.Column("comment", sa.String(length=255), nullable=True),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["core.requester.id"],
            name=op.f("fk_contact_requester_id_requester"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
        schema="core",
    )
    op.create_table(
        "taxable_income",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("income", sa.Integer(), nullable=True),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["core.requester.id"],
            name=op.f("fk_taxable_income_requester_id_requester"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taxable_income")),
        schema="core",
    )
    op.create_table(
        "project",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column("work_type", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=2083), nullable=True),
        sa.Column("manager_id", sa.Integer(), nullable=True),
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["manager_id"], ["core.user.id"], name=op.f("fk_project_manager_id_user")
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["core.mission.id"],
            name=op.f("fk_project_mission_id_mission"),
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["core.requester.id"],
            name=op.f("fk_project_requester_id_requester"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
        sa.UniqueConstraint("requester_id", name=op.f("uq_project_requester_id")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project", schema="core")
    op.drop_table("taxable_income", schema="core")
    op.drop_table("contact", schema="core")
    op.drop_table("requester", schema="core")
    # ### end Alembic commands ###
