"""Add soft delete column to Mission

Revision ID: 01865af35138
Revises: f6e588288616
Create Date: 2020-04-21 12:04:12.392416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "01865af35138"
down_revision = "f6e588288616"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mission", sa.Column("is_deleted", sa.Boolean(), nullable=True), schema="core"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mission", "is_deleted", schema="core")
    # ### end Alembic commands ###
