"""quote table

Revision ID: 80789b55bb1f
Revises: 66e6fad5485d
Create Date: 2020-05-25 15:48:51.860246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80789b55bb1f"
down_revision = "66e6fad5485d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quote",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("is_bill", sa.Boolean(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("precision", sa.String(length=255), nullable=True),
        sa.Column("price_excl_tax", sa.Float(), nullable=True),
        sa.Column("price_incl_tax", sa.Float(), nullable=True),
        sa.Column("eligible_amount", sa.Float(), nullable=True),
        sa.Column("note", sa.String(length=2083), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quote", schema="core")
    # ### end Alembic commands ###
