"""implement phones requesters

Revision ID: 6fd49562b05d
Revises: f6e588288616
Create Date: 2020-04-21 16:17:37.950864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6fd49562b05d"
down_revision = "01865af35138"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contact", "phone_number", schema="core")
    op.drop_column("requester", "phone_number_1", schema="core")
    op.drop_column("requester", "phone_number_2", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requester",
        sa.Column(
            "phone_number_2", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        schema="core",
    )
    op.add_column(
        "requester",
        sa.Column(
            "phone_number_1",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        schema="core",
    )
    op.add_column(
        "contact",
        sa.Column(
            "phone_number", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        schema="core",
    )
    # ### end Alembic commands ###
