"""remove_manager_project

Revision ID: d467567d9b98
Revises: f8d81ff5a3c8
Create Date: 2020-04-16 09:17:00.961939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d467567d9b98"
down_revision = "f8d81ff5a3c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_project_manager_id_user", "project", schema="core", type_="foreignkey"
    )
    op.drop_column("project", "manager_id", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("manager_id", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="core",
    )
    op.create_foreign_key(
        "fk_project_manager_id_user",
        "project",
        "user",
        ["manager_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    # ### end Alembic commands ###
