"""comments table

Revision ID: f92d3ced7380
Revises: 09703cacc1ac
Create Date: 2020-05-06 15:04:01.554606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f92d3ced7380"
down_revision = "981991a1a4ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content", sa.String(length=2083), nullable=True),
        sa.Column("is_important", sa.Boolean(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["core.user.id"], name=op.f("fk_comment_author_id_user")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["core.project.id"],
            name=op.f("fk_comment_project_id_project"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment", schema="core")
    # ### end Alembic commands ###
