"""Unique Agency name

Revision ID: e2e96d918b5b
Revises: 01865af35138
Create Date: 2020-04-21 14:52:02.856436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2e96d918b5b"
down_revision = "6fd49562b05d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_agency_name"), "agency", ["name"], schema="core"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_agency_name"), "agency", schema="core", type_="unique")
    # ### end Alembic commands ###
