"""simulations notes

Revision ID: f8fca8b7e4c5
Revises: 1c89df0bd4d9
Create Date: 2020-06-19 15:42:00.304924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f8fca8b7e4c5"
down_revision = "1c89df0bd4d9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulation",
        sa.Column("note_certifications", sa.String(length=2083), nullable=True),
        schema="core",
    )
    op.add_column(
        "simulation",
        sa.Column("note_deposits", sa.String(length=2083), nullable=True),
        schema="core",
    )
    op.add_column(
        "simulation",
        sa.Column("note_payment_requests", sa.String(length=2083), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulation", "note_payment_requests", schema="core")
    op.drop_column("simulation", "note_deposits", schema="core")
    op.drop_column("simulation", "note_certifications", schema="core")
    # ### end Alembic commands ###
