"""quote project relation

Revision ID: 3e4fb7d8b121
Revises: 80789b55bb1f
Create Date: 2020-05-25 16:15:17.428472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e4fb7d8b121"
down_revision = "80789b55bb1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quote", sa.Column("project_id", sa.Integer(), nullable=False), schema="core"
    )
    op.create_foreign_key(
        op.f("fk_quote_project_id_project"),
        "quote",
        "project",
        ["project_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_quote_project_id_project"), "quote", schema="core", type_="foreignkey"
    )
    op.drop_column("quote", "project_id", schema="core")
    # ### end Alembic commands ###
