"""Add work_type

Revision ID: 1b7fb2899b9d
Revises: 01ccb957938f
Create Date: 2020-05-14 14:40:32.963523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b7fb2899b9d"
down_revision = "01ccb957938f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_type",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type_name", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["core.project.id"],
            name=op.f("fk_work_type_project_id_project"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_type")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("work_type", schema="core")
    # ### end Alembic commands ###
