"""add funders

Revision ID: 480d8160e141
Revises: f92d3ced7380
Create Date: 2020-05-11 17:06:08.055033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "480d8160e141"
down_revision = "f92d3ced7380"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funder",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("subvention_round", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["core.mission.id"],
            name=op.f("fk_funder_mission_id_mission"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_funder")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("funder", schema="core")
    # ### end Alembic commands ###
