"""recreate simulationfunder

Revision ID: 23acaac06ed0
Revises: 1ed354f8973e
Create Date: 2020-06-09 15:28:40.998242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23acaac06ed0"
down_revision = "1ed354f8973e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_funder",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("base_funder_id", sa.Integer(), nullable=True),
        sa.Column("duplicate_funder_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_funder_id"],
            ["core.funder.id"],
            name=op.f("fk_simulation_funder_base_funder_id_funder"),
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_funder_id"],
            ["core.funder.id"],
            name=op.f("fk_simulation_funder_duplicate_funder_id_funder"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_funder")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("simulation_funder", schema="core")
    # ### end Alembic commands ###
