"""quotes_work_types

Revision ID: 217ddec57f4e
Revises: 3e4fb7d8b121
Create Date: 2020-05-26 10:54:06.361623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "217ddec57f4e"
down_revision = "3e4fb7d8b121"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quote_work_type",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type_name", sa.String(length=255), nullable=False),
        sa.Column("quote_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["core.quote.id"],
            name=op.f("fk_quote_work_type_quote_id_quote"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_work_type")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quote_work_type", schema="core")
    # ### end Alembic commands ###
