"""Phone Number

Revision ID: c43dc508a276
Revises: 95a12d6d99e0
Create Date: 2020-04-16 13:22:32.270303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c43dc508a276"
down_revision = "95a12d6d99e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phone_number",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country_code", sa.String(length=3), nullable=False),
        sa.Column("national", sa.String(length=128), nullable=False),
        sa.Column("international", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=128), nullable=True),
        sa.Column("resource_type", sa.String(length=128), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phone_number")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("phone_number", schema="core")
    # ### end Alembic commands ###
