"""accommodation_missing_fields

Revision ID: 014673597f25
Revises: 08693b60845d
Create Date: 2020-06-30 16:50:56.938500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "014673597f25"
down_revision = "08693b60845d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accommodation",
        sa.Column("access", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "accommodation",
        sa.Column("type_rent_after_renovation", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "requester",
        sa.Column("has_AAH", sa.Boolean(create_constraint=False), nullable=True),
        schema="core",
    )
    op.add_column(
        "requester",
        sa.Column("has_APA", sa.Boolean(create_constraint=False), nullable=True),
        schema="core",
    )
    op.drop_column("requester", "have_APA", schema="core")
    op.drop_column("requester", "have_AAH", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requester",
        sa.Column("have_AAH", sa.BOOLEAN(), autoincrement=False, nullable=True),
        schema="core",
    )
    op.add_column(
        "requester",
        sa.Column("have_APA", sa.BOOLEAN(), autoincrement=False, nullable=True),
        schema="core",
    )
    op.drop_column("requester", "has_APA", schema="core")
    op.drop_column("requester", "has_AAH", schema="core")
    op.drop_column("accommodation", "type_rent_after_renovation", schema="core")
    op.drop_column("accommodation", "access", schema="core")
    # ### end Alembic commands ###
