"""rename supervisor

Revision ID: 95a12d6d99e0
Revises: cc93106bcf2d
Create Date: 2020-04-16 11:34:29.755123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "95a12d6d99e0"
down_revision = "cc93106bcf2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_lead",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["core.project.id"],
            name=op.f("fk_project_lead_project_id_project"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["core.user.id"], name=op.f("fk_project_lead_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_lead")),
        schema="core",
    )
    op.drop_table("supervisor", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supervisor",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('core.supervisor_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["core.project.id"], name="fk_supervisor_project_id_project"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["core.user.id"], name="fk_supervisor_user_id_user"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_supervisor"),
        schema="core",
    )
    op.drop_table("project_lead", schema="core")
    # ### end Alembic commands ###
