"""remove_clone_quotes

Revision ID: e24ca003fb02
Revises: 00e8fbb91c13
Create Date: 2020-06-17 14:53:32.433687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e24ca003fb02"
down_revision = "00e8fbb91c13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_simulation_quote_duplicate_quote_id_quote",
        "simulation_quote",
        schema="core",
        type_="foreignkey",
    )
    op.drop_column("simulation_quote", "duplicate_quote_id", schema="core")
    op.drop_column("simulation_quote", "modification_date", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulation_quote",
        sa.Column(
            "modification_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        schema="core",
    )
    op.add_column(
        "simulation_quote",
        sa.Column(
            "duplicate_quote_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        schema="core",
    )
    op.create_foreign_key(
        "fk_simulation_quote_duplicate_quote_id_quote",
        "simulation_quote",
        "quote",
        ["duplicate_quote_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    # ### end Alembic commands ###
