"""active_constraint

Revision ID: cc93106bcf2d
Revises: b5b04084cb67
Create Date: 2020-04-16 10:25:43.919500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc93106bcf2d"
down_revision = "b5b04084cb67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project", "active", existing_type=sa.BOOLEAN(), nullable=False, schema="core"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project", "active", existing_type=sa.BOOLEAN(), nullable=True, schema="core"
    )
    # ### end Alembic commands ###
