"""remove_accommodation_id

Revision ID: 8231ff267283
Revises: 41e1e8d065d8
Create Date: 2020-06-30 12:56:56.833628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8231ff267283"
down_revision = "41e1e8d065d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_project_accommodation_id", "project", schema="core", type_="unique"
    )
    op.drop_constraint(
        "fk_project_accommodation_id_accommodation",
        "project",
        schema="core",
        type_="foreignkey",
    )
    op.drop_column("project", "accommodation_id", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("accommodation_id", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="core",
    )
    op.create_foreign_key(
        "fk_project_accommodation_id_accommodation",
        "project",
        "accommodation",
        ["accommodation_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    op.create_unique_constraint(
        "uq_project_accommodation_id", "project", ["accommodation_id"], schema="core"
    )
    # ### end Alembic commands ###
