"""add user_id to search

Revision ID: 09703cacc1ac
Revises: a0eb8c693b7a
Create Date: 2020-04-23 14:26:19.053731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09703cacc1ac"
down_revision = "a0eb8c693b7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "search", sa.Column("user_id", sa.Integer(), nullable=True), schema="core"
    )
    op.create_foreign_key(
        op.f("fk_search_user_id_user"),
        "search",
        "user",
        ["user_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_search_user_id_user"), "search", schema="core", type_="foreignkey"
    )
    op.drop_column("search", "user_id", schema="core")
    # ### end Alembic commands ###
