"""simulation_calcul_variables

Revision ID: 41e1e8d065d8
Revises: f8fca8b7e4c5
Create Date: 2020-06-24 10:37:01.956614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41e1e8d065d8"
down_revision = "f8fca8b7e4c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulation_funder",
        sa.Column("advance", sa.Integer(), nullable=True),
        schema="core",
    )
    op.add_column(
        "simulation_funder",
        sa.Column("rate", sa.Integer(), nullable=True),
        schema="core",
    )
    op.add_column(
        "simulation_funder",
        sa.Column("subventioned_expense", sa.Integer(), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulation_funder", "subventioned_expense", schema="core")
    op.drop_column("simulation_funder", "rate", schema="core")
    op.drop_column("simulation_funder", "advance", schema="core")
    # ### end Alembic commands ###
