"""add funding scenarios

Revision ID: ce8f21ffbe03
Revises: c567daee4a72
Create Date: 2020-05-19 14:40:38.386420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ce8f21ffbe03"
down_revision = "c567daee4a72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funding_scenario",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criteria", sa.JSON(), nullable=False),
        sa.Column("rate", sa.Integer(), nullable=False),
        sa.Column("upper_limit", sa.Integer(), nullable=True),
        sa.Column("advance", sa.Integer(), nullable=True),
        sa.Column("funder_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["funder_id"],
            ["core.funder.id"],
            name=op.f("fk_funding_scenario_funder_id_funder"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_funding_scenario")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("funding_scenario", schema="core")
    # ### end Alembic commands ###
