"""add_commentary_monitoring_project_side

Revision ID: eb869c77fa8a
Revises: dbdd503a9409
Create Date: 2020-09-01 16:52:52.639407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb869c77fa8a"
down_revision = "dbdd503a9409"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("monitoring_commentary", sa.String(length=2083), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "monitoring_commentary", schema="core")
    # ### end Alembic commands ###
