"""funder_monitoring_value

Revision ID: 205c27a03e8b
Revises: 4313cb3aa8fa
Create Date: 2020-08-25 16:11:02.352154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "205c27a03e8b"
down_revision = "4313cb3aa8fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funders_monitoring_values",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("funder_id", sa.Integer(), nullable=True),
        sa.Column("monitor_field_id", sa.Integer(), nullable=True),
        sa.Column("date_value", sa.Date(), nullable=True),
        sa.Column("boolean_value", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["funder_id"],
            ["core.funder.id"],
            name=op.f("fk_funders_monitoring_values_funder_id_funder"),
        ),
        sa.ForeignKeyConstraint(
            ["monitor_field_id"],
            ["core.monitor_field.id"],
            name=op.f("fk_funders_monitoring_values_monitor_field_id_monitor_field"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["core.project.id"],
            name=op.f("fk_funders_monitoring_values_project_id_project"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_funders_monitoring_values")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("funders_monitoring_values", schema="core")
    # ### end Alembic commands ###
