"""Add no_advance_request field

Revision ID: 6a25c1265d86
Revises: e96e946952d8
Create Date: 2020-09-14 10:37:31.655264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6a25c1265d86"
down_revision = "990b4f51ba67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("no_advance_request", sa.Boolean(), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "no_advance_request", schema="core")
    # ### end Alembic commands ###
