"""FunderAccommodation join

Revision ID: cab37c322768
Revises: 249ba82a1f68
Create Date: 2020-07-27 15:48:50.240839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cab37c322768"
down_revision = "249ba82a1f68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "funder_accommodations",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("simulation_funder_id", sa.Integer(), nullable=True),
        sa.Column("simulation_accommodation_id", sa.Integer(), nullable=True),
        sa.Column("is_common_area", sa.Boolean(), nullable=True),
        sa.Column("advance", sa.Integer(), nullable=True),
        sa.Column("subventioned_expense", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["simulation_accommodation_id"],
            ["core.simulation_accommodation.id"],
            name=op.f(
                "fk_funder_accommodations_simulation_accommodation_id_simulation_accommodation"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["simulation_funder_id"],
            ["core.simulation_funder.id"],
            name=op.f(
                "fk_funder_accommodations_simulation_funder_id_simulation_funder"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_funder_accommodations")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("funder_accommodations", schema="core")
    # ### end Alembic commands ###
