"""fix funder accommodation model

Revision ID: 3afe7e97d456
Revises: b216f2b0b1d3
Create Date: 2020-07-30 13:47:40.137134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3afe7e97d456"
down_revision = "b216f2b0b1d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "funder_accommodations",
        "rate",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=True,
        schema="core",
    )
    op.drop_column("funder_accommodations", "advance", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "funder_accommodations",
        sa.Column(
            "advance",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="core",
    )
    op.alter_column(
        "funder_accommodations",
        "rate",
        existing_type=sa.Integer(),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
        schema="core",
    )
    # ### end Alembic commands ###
