"""link areas walls ceilings

Revision ID: 656d9ddd3828
Revises: ba29a7066a86
Create Date: 2020-12-10 15:28:49.233022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "656d9ddd3828"
down_revision = "5313c5e22eee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "area", sa.Column("ceiling_id", sa.Integer(), nullable=True), schema="core"
    )
    op.add_column(
        "area",
        sa.Column("number_identical_woodwork", sa.Integer(), nullable=True),
        schema="core",
    )
    op.add_column(
        "area", sa.Column("wall_id", sa.Integer(), nullable=True), schema="core"
    )
    op.create_foreign_key(
        op.f("fk_area_wall_id_wall"),
        "area",
        "wall",
        ["wall_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    op.create_foreign_key(
        op.f("fk_area_ceiling_id_ceiling"),
        "area",
        "ceiling",
        ["ceiling_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_area_ceiling_id_ceiling"), "area", schema="core", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_area_wall_id_wall"), "area", schema="core", type_="foreignkey"
    )
    op.drop_column("area", "wall_id", schema="core")
    op.drop_column("area", "number_identical_woodwork", schema="core")
    op.drop_column("area", "ceiling_id", schema="core")
    # ### end Alembic commands ###
