"""expand QuoteAccommodation

Revision ID: ccb2bdbc99c8
Revises: 254c6d1cd095
Create Date: 2020-07-22 11:22:24.923319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ccb2bdbc99c8"
down_revision = "254c6d1cd095"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quote_accommodation",
        sa.Column("eligible_amount", sa.Float(), nullable=True),
        schema="core",
    )
    op.add_column(
        "quote_accommodation",
        sa.Column("price_excl_tax", sa.Float(), nullable=True),
        schema="core",
    )
    op.add_column(
        "quote_accommodation",
        sa.Column("price_incl_tax", sa.Float(), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quote_accommodation", "price_incl_tax", schema="core")
    op.drop_column("quote_accommodation", "price_excl_tax", schema="core")
    op.drop_column("quote_accommodation", "eligible_amount", schema="core")
    # ### end Alembic commands ###
