"""expand common area model

Revision ID: 7f7c044ba088
Revises: a51d41774547
Create Date: 2020-07-20 15:22:01.322945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f7c044ba088"
down_revision = "a51d41774547"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "common_area", sa.Column("area", sa.Float(), nullable=True), schema="core"
    )
    op.add_column(
        "common_area",
        sa.Column("degradation_coefficient", sa.Float(), nullable=True),
        schema="core",
    )
    op.add_column(
        "common_area",
        sa.Column("note", sa.String(length=800), nullable=True),
        schema="core",
    )
    op.add_column(
        "common_area",
        sa.Column("unsanitary_coefficient", sa.Float(), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("common_area", "unsanitary_coefficient", schema="core")
    op.drop_column("common_area", "note", schema="core")
    op.drop_column("common_area", "degradation_coefficient", schema="core")
    op.drop_column("common_area", "area", schema="core")
    # ### end Alembic commands ###
