"""rooms input and areas

Revision ID: f7d30b0759f9
Revises: f021d0ee94a1
Create Date: 2020-10-30 12:14:58.031821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7d30b0759f9"
down_revision = "f021d0ee94a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room_input",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.Boolean(create_constraint=255), nullable=True),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.Column("wall_id", sa.Integer(), nullable=True),
        sa.Column("woodwork_id", sa.Integer(), nullable=True),
        sa.Column("ceiling_id", sa.Integer(), nullable=True),
        sa.Column("floor_id", sa.Integer(), nullable=True),
        sa.Column("thermal_bridge_id", sa.Integer(), nullable=True),
        sa.Column("number_identical_woodwork", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ceiling_id"],
            ["core.ceiling.id"],
            name=op.f("fk_room_input_ceiling_id_ceiling"),
        ),
        sa.ForeignKeyConstraint(
            ["floor_id"], ["core.floor.id"], name=op.f("fk_room_input_floor_id_floor")
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["core.room.id"], name=op.f("fk_room_input_room_id_room")
        ),
        sa.ForeignKeyConstraint(
            ["thermal_bridge_id"],
            ["core.thermal_bridge.id"],
            name=op.f("fk_room_input_thermal_bridge_id_thermal_bridge"),
        ),
        sa.ForeignKeyConstraint(
            ["wall_id"], ["core.wall.id"], name=op.f("fk_room_input_wall_id_wall")
        ),
        sa.ForeignKeyConstraint(
            ["woodwork_id"],
            ["core.woodwork.id"],
            name=op.f("fk_room_input_woodwork_id_woodwork"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_input")),
        schema="core",
    )
    op.create_table(
        "area",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.Column("room_input_id", sa.Integer(), nullable=True),
        sa.Column("length", sa.Float(), nullable=True),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"], ["core.room.id"], name=op.f("fk_area_room_id_room")
        ),
        sa.ForeignKeyConstraint(
            ["room_input_id"],
            ["core.room_input.id"],
            name=op.f("fk_area_room_input_id_room_input"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_area")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("area", schema="core")
    op.drop_table("room_input", schema="core")
    # ### end Alembic commands ###
