"""wall kwnown value to str

Revision ID: 238e6c3038cc
Revises: 95ccbd8cf491
Create Date: 2020-12-15 13:58:36.015141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "238e6c3038cc"
down_revision = "95ccbd8cf491"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wall",
        "known_value",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.String(length=255),
        existing_nullable=True,
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wall",
        "known_value",
        existing_type=sa.String(length=255),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
        schema="core",
    )
    # ### end Alembic commands ###
