"""data import model

Revision ID: 793c8785df99
Revises: b691f0d07a41
Create Date: 2020-10-12 10:50:26.478916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "793c8785df99"
down_revision = "b691f0d07a41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_import",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("status", sa.String(length=255), nullable=True),
        sa.Column("user_email", sa.String(length=255), nullable=True),
        sa.Column("data", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_import")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_import", schema="core")
    # ### end Alembic commands ###
