"""app_config table

Revision ID: 5ac850ea2d37
Revises: dded725aa928
Create Date: 2020-12-07 14:44:51.257574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ac850ea2d37"
down_revision = "dded725aa928"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_config",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=800), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_config")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_config", schema="core")
    # ### end Alembic commands ###
