"""Add scenario table

Revision ID: 6b13925afe96
Revises: 1064d07db948
Create Date: 2020-10-27 10:56:33.245381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6b13925afe96"
down_revision = "1064d07db948"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenario",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("is_initial_state", sa.Boolean(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("annual_energy_consumption", sa.Float(), nullable=True),
        sa.Column("accommodation_id", sa.Integer(), nullable=True),
        sa.Column("energy_label", sa.String(length=255), nullable=True),
        sa.Column("energy_gain", sa.Integer(), nullable=True),
        sa.Column("annual_GES_emission", sa.Float(), nullable=True),
        sa.Column("GES_label", sa.String(length=255), nullable=True),
        sa.Column("loss_upper_limit", sa.Integer(), nullable=True),
        sa.Column("loss_exterior_wall", sa.Integer(), nullable=True),
        sa.Column("loss_local_wall", sa.Integer(), nullable=True),
        sa.Column("loss_floor", sa.Integer(), nullable=True),
        sa.Column("loss_windows", sa.Integer(), nullable=True),
        sa.Column("loss_doors", sa.Integer(), nullable=True),
        sa.Column("loss_heat_bridges", sa.Integer(), nullable=True),
        sa.Column("loss_airflow", sa.Integer(), nullable=True),
        sa.Column("heat_energy_1_final", sa.Float(), nullable=True),
        sa.Column("heat_energy_1_primary", sa.Float(), nullable=True),
        sa.Column("heat_energy_2_final", sa.Float(), nullable=True),
        sa.Column("heat_energy_2_primary", sa.Float(), nullable=True),
        sa.Column("ECS_energy_1_final", sa.Float(), nullable=True),
        sa.Column("ECS_energy_1_primary", sa.Float(), nullable=True),
        sa.Column("ECS_energy_2_final", sa.Float(), nullable=True),
        sa.Column("ECS_energy_2_primary", sa.Float(), nullable=True),
        sa.Column("cooling_energy_1_final", sa.Float(), nullable=True),
        sa.Column("cooling_energy_1_primary", sa.Float(), nullable=True),
        sa.Column("airflow_device", sa.String(length=255), nullable=True),
        sa.Column("air_conditioning_type", sa.String(length=255), nullable=True),
        sa.Column("air_conditioned_area", sa.Float(), nullable=True),
        sa.Column("has_photovoltaic_device", sa.Boolean(), nullable=True),
        sa.Column("photovoltaic_device_surface", sa.Float(), nullable=True),
        sa.Column("living_area", sa.Float(), nullable=True),
        sa.Column("average_height", sa.Float(), nullable=True),
        sa.Column("inertia", sa.String(length=255), nullable=True),
        sa.Column("altitude", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["core.accommodation.id"],
            name=op.f("fk_scenario_accommodation_id_accommodation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenario")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenario", schema="core")
    # ### end Alembic commands ###
