"""link quote with accommodations

Revision ID: 254c6d1cd095
Revises: 13ce5f46a9d2
Create Date: 2020-07-22 11:20:23.433779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "254c6d1cd095"
down_revision = "13ce5f46a9d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quote_accommodation",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("quote_id", sa.Integer(), nullable=True),
        sa.Column("accommodation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["core.accommodation.id"],
            name=op.f("fk_quote_accommodation_accommodation_id_accommodation"),
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["core.quote.id"],
            name=op.f("fk_quote_accommodation_quote_id_quote"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_accommodation")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quote_accommodation", schema="core")
    # ### end Alembic commands ###
