"""simulations_accommodations table

Revision ID: 249ba82a1f68
Revises: ccb2bdbc99c8
Create Date: 2020-07-24 09:23:29.428869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "249ba82a1f68"
down_revision = "ccb2bdbc99c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_accommodation",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("simulation_id", sa.Integer(), nullable=True),
        sa.Column("accommodation_id", sa.Integer(), nullable=True),
        sa.Column("rent_type", sa.String(length=255), nullable=True),
        sa.Column("rent_per_msq", sa.Float(), nullable=True),
        sa.Column("rent", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["accommodation_id"],
            ["core.accommodation.id"],
            name=op.f("fk_simulation_accommodation_accommodation_id_accommodation"),
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["core.simulation.id"],
            name=op.f("fk_simulation_accommodation_simulation_id_simulation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_accommodation")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("simulation_accommodation", schema="core")
    # ### end Alembic commands ###
