"""scenario commentary

Revision ID: 9b7c70f6f424
Revises: c3c3cd9b01c7
Create Date: 2020-12-07 17:15:18.131667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b7c70f6f424"
down_revision = "c3c3cd9b01c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenario",
        sa.Column("commentary", sa.String(length=800), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scenario", "commentary", schema="core")
    # ### end Alembic commands ###
