"""rooms table

Revision ID: f021d0ee94a1
Revises: de2c83fbc09b
Create Date: 2020-10-30 11:21:38.852421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f021d0ee94a1"
down_revision = "de2c83fbc09b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column("heating_id", sa.Integer(), nullable=True),
        sa.Column("height_under_ceiling", sa.Float(), nullable=True),
        sa.Column("air_conditioning", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["heating_id"], ["core.heating.id"], name=op.f("fk_room_heating_id_heating")
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["core.scenario.id"],
            name=op.f("fk_room_scenario_id_scenario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("room", schema="core")
    # ### end Alembic commands ###
