"""join common_area / disorders

Revision ID: 31c79a1bb808
Revises: 7f7c044ba088
Create Date: 2020-07-20 16:47:13.643909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "31c79a1bb808"
down_revision = "7f7c044ba088"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "disorder",
        sa.Column("common_area_id", sa.Integer(), nullable=True),
        schema="core",
    )
    op.alter_column(
        "disorder",
        "accommodation_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        schema="core",
    )
    op.create_foreign_key(
        op.f("fk_disorder_common_area_id_common_area"),
        "disorder",
        "common_area",
        ["common_area_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_disorder_common_area_id_common_area"),
        "disorder",
        schema="core",
        type_="foreignkey",
    )
    op.alter_column(
        "disorder",
        "accommodation_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        schema="core",
    )
    op.drop_column("disorder", "common_area_id", schema="core")
    # ### end Alembic commands ###
