"""heating table

Revision ID: 66d734c87f4f
Revises: 6b13925afe96
Create Date: 2020-10-27 11:16:51.221447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "66d734c87f4f"
down_revision = "6b13925afe96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heating",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column("heating_name", sa.String(length=255), nullable=True),
        sa.Column("emissions_type", sa.String(length=255), nullable=True),
        sa.Column("energy_used", sa.String(length=255), nullable=True),
        sa.Column("generator_type", sa.String(length=255), nullable=True),
        sa.Column("is_power_known", sa.Boolean(), nullable=True),
        sa.Column("power", sa.Integer(), nullable=True),
        sa.Column("has_regulation", sa.Boolean(), nullable=True),
        sa.Column("wall_mounted_boiler", sa.Boolean(), nullable=True),
        sa.Column("isolated_network", sa.Boolean(), nullable=True),
        sa.Column("emettor_type", sa.String(length=255), nullable=True),
        sa.Column("installation_year", sa.String(length=255), nullable=True),
        sa.Column("intermittent_equipment", sa.String(length=255), nullable=True),
        sa.Column("wood_oven", sa.Boolean(), nullable=True),
        sa.Column("equipment_performance", sa.String(length=255), nullable=True),
        sa.Column("heated_area", sa.Float(), nullable=True),
        sa.Column("known_caracteristics", sa.Boolean(), nullable=True),
        sa.Column("full_yield", sa.Float(), nullable=True),
        sa.Column("middle_yield", sa.Float(), nullable=True),
        sa.Column("COP", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["core.scenario.id"],
            name=op.f("fk_heating_scenario_id_scenario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_heating")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("heating", schema="core")
    # ### end Alembic commands ###
