"""add error field to email

Revision ID: ca9dcb8eb5e2
Revises: 5a9994bed9ec
Create Date: 2020-09-08 16:15:47.564268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ca9dcb8eb5e2"
down_revision = "5a9994bed9ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("email", sa.Column("error", sa.Text(), nullable=True), schema="core")
    op.drop_column("email", "sender_email", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email",
        sa.Column(
            "sender_email", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        schema="core",
    )
    op.drop_column("email", "error", schema="core")
    # ### end Alembic commands ###
