"""client_access_mission

Revision ID: 8290571869e3
Revises: a5881854fc52
Create Date: 2020-09-29 15:45:33.528557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8290571869e3"
down_revision = "a5881854fc52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mission",
        sa.Column("ca_accommodation", sa.Boolean(), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("ca_accommodation_summary", sa.Boolean(), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("ca_certification", sa.Boolean(), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("ca_common_area", sa.Boolean(), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission", sa.Column("ca_deposit", sa.Boolean(), nullable=True), schema="core"
    )
    op.add_column(
        "mission", sa.Column("ca_documents", sa.Boolean(), nullable=True), schema="core"
    )
    op.add_column(
        "mission", sa.Column("ca_follow_up", sa.Boolean(), nullable=True), schema="core"
    )
    op.add_column(
        "mission", sa.Column("ca_funders", sa.Boolean(), nullable=True), schema="core"
    )
    op.add_column(
        "mission",
        sa.Column("ca_payment_request", sa.Boolean(), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission", sa.Column("ca_quotes", sa.Boolean(), nullable=True), schema="core"
    )
    op.add_column(
        "mission", sa.Column("ca_requester", sa.Boolean(), nullable=True), schema="core"
    )
    op.add_column(
        "mission",
        sa.Column("ca_simulations", sa.Boolean(), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mission", "ca_simulations", schema="core")
    op.drop_column("mission", "ca_requester", schema="core")
    op.drop_column("mission", "ca_quotes", schema="core")
    op.drop_column("mission", "ca_payment_request", schema="core")
    op.drop_column("mission", "ca_funders", schema="core")
    op.drop_column("mission", "ca_follow_up", schema="core")
    op.drop_column("mission", "ca_documents", schema="core")
    op.drop_column("mission", "ca_deposit", schema="core")
    op.drop_column("mission", "ca_common_area", schema="core")
    op.drop_column("mission", "ca_certification", schema="core")
    op.drop_column("mission", "ca_accommodation_summary", schema="core")
    op.drop_column("mission", "ca_accommodation", schema="core")
    # ### end Alembic commands ###
