"""fix bad scenario field naming

Revision ID: 45c8f9c6133b
Revises: abd044c39025
Create Date: 2020-11-03 16:45:34.768490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45c8f9c6133b"
down_revision = "abd044c39025"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenario",
        sa.Column("loss_ceiling", sa.Integer(), nullable=True),
        schema="core",
    )
    op.drop_column("scenario", "loss_upper_limit", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenario",
        sa.Column("loss_upper_limit", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="core",
    )
    op.drop_column("scenario", "loss_ceiling", schema="core")
    # ### end Alembic commands ###
