"""monitor_fields

Revision ID: 4313cb3aa8fa
Revises: c3b546e0852c
Create Date: 2020-08-25 15:46:47.534505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4313cb3aa8fa"
down_revision = "c3b546e0852c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitor_field",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=False),
        sa.Column("invisible", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["monitor_id"],
            ["core.monitor.id"],
            name=op.f("fk_monitor_field_monitor_id_monitor"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitor_field")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("monitor_field", schema="core")
    # ### end Alembic commands ###
