"""funder_simulations_values_int_to_float

Revision ID: b216f2b0b1d3
Revises: 8cb2c432699c
Create Date: 2020-07-28 17:19:27.024253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b216f2b0b1d3"
down_revision = "8cb2c432699c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "funder_accommodations",
        "advance",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "funder_accommodations",
        "rate",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "funder_accommodations",
        "subventioned_expense",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "simulation_funder",
        "advance",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "simulation_funder",
        "subventioned_expense",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "simulation_funder",
        "subventioned_expense",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "simulation_funder",
        "advance",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "funder_accommodations",
        "subventioned_expense",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "funder_accommodations",
        "rate",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "funder_accommodations",
        "advance",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        schema="core",
    )
    # ### end Alembic commands ###
