"""available field values

Revision ID: c85c0ef5a19e
Revises: d2339d244d9d
Create Date: 2020-07-31 18:31:05.088016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c85c0ef5a19e"
down_revision = "d2339d244d9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "available_field_value",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("value", sa.String(length=800), nullable=True),
        sa.Column("custom_field_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["custom_field_id"],
            ["core.custom_field.id"],
            name=op.f("fk_available_field_value_custom_field_id_custom_field"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_available_field_value")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("available_field_value", schema="core")
    # ### end Alembic commands ###
