"""thermal bridge table

Revision ID: 3455482e7a18
Revises: 2f6886b3118c
Create Date: 2020-10-29 15:44:48.320441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3455482e7a18"
down_revision = "2f6886b3118c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thermal_bridge",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("length_m_liaison", sa.Float(), nullable=True),
        sa.Column("wall_name", sa.String(length=255), nullable=True),
        sa.Column("floor_name", sa.String(length=255), nullable=True),
        sa.Column("ceiling_name", sa.String(length=255), nullable=True),
        sa.Column("position_medium_floor", sa.String(length=255), nullable=True),
        sa.Column("position_shear_wall", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["core.scenario.id"],
            name=op.f("fk_thermal_bridge_scenario_id_scenario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thermal_bridge")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thermal_bridge", schema="core")
    # ### end Alembic commands ###
