"""update funder_accommodation

Revision ID: 990b4f51ba67
Revises: eb869c77fa8a
Create Date: 2020-09-08 14:17:35.349932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "990b4f51ba67"
down_revision = "e96e946952d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "funder_accommodations",
        sa.Column("accommodation_id", sa.Integer(), nullable=True),
        schema="core",
    )
    op.add_column(
        "funder_accommodations",
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        schema="core",
    )
    op.drop_constraint(
        "fk_funder_accommodations_simulation_accommodation_id_si_010c",
        "funder_accommodations",
        schema="core",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_funder_accommodations_scenario_id_funding_scenario"),
        "funder_accommodations",
        "funding_scenario",
        ["scenario_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    op.create_foreign_key(
        op.f("fk_funder_accommodations_accommodation_id_accommodation"),
        "funder_accommodations",
        "accommodation",
        ["accommodation_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    op.drop_column(
        "funder_accommodations", "simulation_accommodation_id", schema="core"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "funder_accommodations",
        sa.Column(
            "simulation_accommodation_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        schema="core",
    )
    op.drop_constraint(
        op.f("fk_funder_accommodations_accommodation_id_accommodation"),
        "funder_accommodations",
        schema="core",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_funder_accommodations_scenario_id_funding_scenario"),
        "funder_accommodations",
        schema="core",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_funder_accommodations_simulation_accommodation_id_si_010c",
        "funder_accommodations",
        "simulation_accommodation",
        ["simulation_accommodation_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    op.drop_column("funder_accommodations", "scenario_id", schema="core")
    op.drop_column("funder_accommodations", "accommodation_id", schema="core")
    # ### end Alembic commands ###
