"""project_custom_fields link

Revision ID: d2339d244d9d
Revises: 0ea9806d4473
Create Date: 2020-07-30 18:02:32.993438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d2339d244d9d"
down_revision = "0ea9806d4473"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_custom_field",
        sa.Column("project_id", sa.Integer(), nullable=True),
        schema="core",
    )
    op.create_foreign_key(
        op.f("fk_project_custom_field_project_id_project"),
        "project_custom_field",
        "project",
        ["project_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_project_custom_field_project_id_project"),
        "project_custom_field",
        schema="core",
        type_="foreignkey",
    )
    op.drop_column("project_custom_field", "project_id", schema="core")
    # ### end Alembic commands ###
