"""woodworks model

Revision ID: 87a1e0a2e886
Revises: 77e9cd200f9a
Create Date: 2020-10-29 13:01:45.807778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87a1e0a2e886"
down_revision = "77e9cd200f9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "woodwork",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column("door_name", sa.String(length=255), nullable=True),
        sa.Column("windows_name", sa.String(length=255), nullable=True),
        sa.Column("type_election", sa.String(length=255), nullable=True),
        sa.Column("woodwork_known_U_value", sa.Boolean(), nullable=True),
        sa.Column("woodwork_U_value", sa.Float(), nullable=True),
        sa.Column("door_nature", sa.String(length=255), nullable=True),
        sa.Column("door_type", sa.String(length=255), nullable=True),
        sa.Column("door_known_U_value", sa.Boolean(), nullable=True),
        sa.Column("door_U_value", sa.Float(), nullable=True),
        sa.Column("Ujn_value", sa.Float(), nullable=True),
        sa.Column("glass_wall_type", sa.String(length=255), nullable=True),
        sa.Column("windows_type", sa.String(length=255), nullable=True),
        sa.Column("materials", sa.String(length=255), nullable=True),
        sa.Column("glass_type", sa.String(length=255), nullable=True),
        sa.Column("glass_insulated", sa.Boolean(), nullable=True),
        sa.Column("argon_krypton_filling", sa.Boolean(), nullable=True),
        sa.Column("thickness_air_gap", sa.Integer(), nullable=True),
        sa.Column("closing_type", sa.String(length=255), nullable=True),
        sa.Column("inclination", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["core.scenario.id"],
            name=op.f("fk_woodwork_scenario_id_scenario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_woodwork")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("woodwork", schema="core")
    # ### end Alembic commands ###
