"""rm room_input number woodwork

Revision ID: 4921447dcbd1
Revises: 656d9ddd3828
Create Date: 2020-12-11 18:07:17.383943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4921447dcbd1"
down_revision = "656d9ddd3828"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room_input", "number_identical_woodwork", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "room_input",
        sa.Column(
            "number_identical_woodwork",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        schema="core",
    )
    # ### end Alembic commands ###
