"""remove calculated keys from scenario

Revision ID: b643ce814814
Revises: 45c8f9c6133b
Create Date: 2020-11-04 18:35:00.075220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b643ce814814"
down_revision = "45c8f9c6133b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scenario", "living_area", schema="core")
    op.drop_column("scenario", "average_height", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenario",
        sa.Column(
            "average_height",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="core",
    )
    op.add_column(
        "scenario",
        sa.Column(
            "living_area",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        schema="core",
    )
    # ### end Alembic commands ###
