"""project_custom_fields

Revision ID: 0ea9806d4473
Revises: 77e00d6f0b79
Create Date: 2020-07-30 17:25:44.452680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ea9806d4473"
down_revision = "77e00d6f0b79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_custom_field",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("value", sa.String(length=800), nullable=True),
        sa.Column("custom_field_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["custom_field_id"],
            ["core.custom_field.id"],
            name=op.f("fk_project_custom_field_custom_field_id_custom_field"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_custom_field")),
        schema="core",
    )
    op.create_table(
        "custom_field_value",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("value", sa.String(length=800), nullable=True),
        sa.Column("project_custom_field_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_custom_field_id"],
            ["core.project_custom_field.id"],
            name=op.f(
                "fk_custom_field_value_project_custom_field_id_project_custom_field"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_field_value")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("custom_field_value", schema="core")
    op.drop_table("project_custom_field", schema="core")
    # ### end Alembic commands ###
