"""enums index to integer

Revision ID: 4c14f42388e9
Revises: 1ad5a0600b9c
Create Date: 2020-10-26 14:24:58.137947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c14f42388e9"
down_revision = "1ad5a0600b9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "perrenoud_enum",
        sa.Column("index", sa.Integer(), nullable=False),
        schema="core",
    )
    op.drop_column("perrenoud_enum", "kind", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "perrenoud_enum",
        sa.Column("kind", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        schema="core",
    )
    op.drop_column("perrenoud_enum", "index", schema="core")
    # ### end Alembic commands ###
