"""mission_funder_monitors

Revision ID: c3b546e0852c
Revises: c85c0ef5a19e
Create Date: 2020-08-25 15:35:51.651243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3b546e0852c"
down_revision = "c85c0ef5a19e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitor",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=True),
        sa.Column("advance_alert", sa.Integer(), nullable=True),
        sa.Column("payment_alert", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["core.mission.id"],
            name=op.f("fk_monitor_mission_id_mission"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitor")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("monitor", schema="core")
    # ### end Alembic commands ###
