"""secondary case type po

Revision ID: 5313c5e22eee
Revises: 5538b675f569
Create Date: 2020-12-14 11:09:10.023303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5313c5e22eee"
down_revision = "5538b675f569"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("secondary_case_type", sa.String(length=255), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "secondary_case_type", schema="core")
    # ### end Alembic commands ###
