"""Project anonymized field

Revision ID: b691f0d07a41
Revises: 2fe79264beb5
Create Date: 2020-10-07 16:15:24.980124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b691f0d07a41"
down_revision = "53e4437c5d0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("anonymized", sa.Boolean(create_constraint=False), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "anonymized", schema="core")
    # ### end Alembic commands ###
