"""funder_accommodation_add_rate

Revision ID: 8cb2c432699c
Revises: cab37c322768
Create Date: 2020-07-27 17:29:43.248983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8cb2c432699c"
down_revision = "cab37c322768"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "funder_accommodations",
        sa.Column("rate", sa.Integer(), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("funder_accommodations", "rate", schema="core")
    # ### end Alembic commands ###
