"""add commentary monitor field

Revision ID: dbdd503a9409
Revises: 8c0af11ae386
Create Date: 2020-08-26 15:35:14.449330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dbdd503a9409"
down_revision = "8c0af11ae386"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitor",
        sa.Column("commentary", sa.String(length=800), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitor", "commentary", schema="core")
    # ### end Alembic commands ###
