"""floor table

Revision ID: 2f6886b3118c
Revises: c4e5efd1f4f4
Create Date: 2020-10-29 14:58:15.517110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f6886b3118c"
down_revision = "c4e5efd1f4f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "floor",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("position", sa.String(length=255), nullable=True),
        sa.Column("perimeter", sa.Float(), nullable=True),
        sa.Column("insulated_heated_non_heated_wall", sa.Boolean(), nullable=True),
        sa.Column("insulated_non_heated_exterior_wall", sa.Boolean(), nullable=True),
        sa.Column("type_non_heated_local", sa.String(length=255), nullable=True),
        sa.Column("known_U_value", sa.Boolean(), nullable=True),
        sa.Column("U_value", sa.Float(), nullable=True),
        sa.Column("main_component", sa.String(length=255), nullable=True),
        sa.Column("insulated_wall", sa.Boolean(), nullable=True),
        sa.Column("known_insulation_value", sa.String(length=255), nullable=True),
        sa.Column("R_value", sa.Float(), nullable=True),
        sa.Column("insulation_thickness", sa.Integer(), nullable=True),
        sa.Column("insulation_type", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["core.scenario.id"],
            name=op.f("fk_floor_scenario_id_scenario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_floor")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("floor", schema="core")
    # ### end Alembic commands ###
