"""scenario cooling energy 2

Revision ID: 95ccbd8cf491
Revises: 4921447dcbd1
Create Date: 2020-12-15 10:51:06.052106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95ccbd8cf491"
down_revision = "4921447dcbd1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenario",
        sa.Column("cooling_energy_2_final", sa.Float(), nullable=True),
        schema="core",
    )
    op.add_column(
        "scenario",
        sa.Column("cooling_energy_2_primary", sa.Float(), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scenario", "cooling_energy_2_primary", schema="core")
    op.drop_column("scenario", "cooling_energy_2_final", schema="core")
    # ### end Alembic commands ###
