"""secondary case type pb

Revision ID: 5538b675f569
Revises: ba29a7066a86
Create Date: 2020-12-14 11:02:01.645128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5538b675f569"
down_revision = "ba29a7066a86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accommodation",
        sa.Column("secondary_case_type", sa.String(length=255), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accommodation", "secondary_case_type", schema="core")
    # ### end Alembic commands ###
