"""email subject no longer required

Revision ID: 69d61b51a9a0
Revises: 2fe79264beb5
Create Date: 2020-10-07 16:58:09.327329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "69d61b51a9a0"
down_revision = "679df370749a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email",
        "subject",
        existing_type=sa.VARCHAR(length=980),
        nullable=True,
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email",
        "subject",
        existing_type=sa.VARCHAR(length=980),
        nullable=False,
        schema="core",
    )
    # ### end Alembic commands ###
