"""dates years to integer

Revision ID: f3ce4872bc66
Revises: debd52b31c95
Create Date: 2020-07-09 10:38:07.872249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import Table, MetaData

revision = "f3ce4872bc66"
down_revision = "debd52b31c95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    meta = MetaData(bind=op.get_bind(), schema="core")

    op.execute(
        "UPDATE core.accommodation SET construction_year = null, purchase_year = null"
    )
    op.execute(
        "UPDATE core.common_area SET construction_year = null, purchase_year = null"
    )
    op.execute("UPDATE core.taxable_income SET date = null")
    op.execute('UPDATE core.requester SET "PTZ_year" = null')

    op.alter_column(
        "accommodation",
        "construction_year",
        existing_type=sa.DATE(),
        type_=sa.Integer(),
        existing_nullable=True,
        schema="core",
        postgresql_using="construction_year::text::integer",
    )
    op.alter_column(
        "accommodation",
        "purchase_year",
        existing_type=sa.DATE(),
        type_=sa.Integer(),
        existing_nullable=True,
        schema="core",
        postgresql_using="purchase_year::text::integer",
    )
    op.alter_column(
        "common_area",
        "construction_year",
        existing_type=sa.DATE(),
        type_=sa.Integer(),
        existing_nullable=True,
        schema="core",
        postgresql_using="construction_year::text::integer",
    )
    op.alter_column(
        "common_area",
        "purchase_year",
        existing_type=sa.DATE(),
        type_=sa.Integer(),
        existing_nullable=True,
        schema="core",
        postgresql_using="purchase_year::text::integer",
    )
    op.alter_column(
        "requester",
        "PTZ_year",
        existing_type=sa.DATE(),
        type_=sa.Integer(),
        existing_nullable=True,
        schema="core",
        postgresql_using='"PTZ_year"::text::integer',
    )
    op.alter_column(
        "taxable_income",
        "date",
        existing_type=sa.DATE(),
        type_=sa.Integer(),
        existing_nullable=True,
        schema="core",
        postgresql_using="date::text::integer",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "taxable_income",
        "date",
        existing_type=sa.Integer(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "requester",
        "PTZ_year",
        existing_type=sa.Integer(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "common_area",
        "purchase_year",
        existing_type=sa.Integer(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "common_area",
        "construction_year",
        existing_type=sa.Integer(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "accommodation",
        "purchase_year",
        existing_type=sa.Integer(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "accommodation",
        "construction_year",
        existing_type=sa.Integer(),
        type_=sa.DATE(),
        existing_nullable=True,
        schema="core",
    )
    # ### end Alembic commands ###
