"""coordinates_string_to_float

Revision ID: 679df370749a
Revises: ee7d8b0c032c
Create Date: 2020-10-06 15:07:44.267926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "679df370749a"
down_revision = "ee7d8b0c032c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project",
        "address_latitude",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Float(),
        existing_nullable=True,
        schema="core",
        postgresql_using="address_latitude::double precision",
    ),
    op.alter_column(
        "project",
        "address_longitude",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Float(),
        existing_nullable=True,
        schema="core",
        postgresql_using="address_longitude::double precision",
    )
    op.alter_column(
        "requester",
        "address_latitude",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Float(),
        existing_nullable=True,
        schema="core",
        postgresql_using="address_latitude::double precision",
    )
    op.alter_column(
        "requester",
        "address_longitude",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Float(),
        existing_nullable=True,
        schema="core",
        postgresql_using="address_longitude::double precision",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "requester",
        "address_longitude",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "requester",
        "address_latitude",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "project",
        "address_longitude",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
        schema="core",
    )
    op.alter_column(
        "project",
        "address_latitude",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
        schema="core",
    )
    # ### end Alembic commands ###
