"""custom_fields

Revision ID: 77e00d6f0b79
Revises: 3afe7e97d456
Create Date: 2020-07-30 14:20:40.174490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77e00d6f0b79"
down_revision = "3afe7e97d456"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_field",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("is_multiple", sa.Boolean(create_constraint=255), nullable=True),
        sa.Column("mission_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["core.mission.id"],
            name=op.f("fk_custom_field_mission_id_mission"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_custom_field")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("custom_field", schema="core")
    # ### end Alembic commands ###
