"""scenario recommendations

Revision ID: ba29a7066a86
Revises: 9b7c70f6f424
Create Date: 2020-12-07 17:36:26.573954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba29a7066a86"
down_revision = "9b7c70f6f424"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recommendation", sa.String(length=255), nullable=True),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column("heating_id", sa.Integer(), nullable=True),
        sa.Column("hot_water_id", sa.Integer(), nullable=True),
        sa.Column("wall_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["heating_id"],
            ["core.heating.id"],
            name=op.f("fk_recommendation_heating_id_heating"),
        ),
        sa.ForeignKeyConstraint(
            ["hot_water_id"],
            ["core.hot_water.id"],
            name=op.f("fk_recommendation_hot_water_id_hot_water"),
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["core.scenario.id"],
            name=op.f("fk_recommendation_scenario_id_scenario"),
        ),
        sa.ForeignKeyConstraint(
            ["wall_id"], ["core.wall.id"], name=op.f("fk_recommendation_wall_id_wall")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recommendation", schema="core")
    # ### end Alembic commands ###
