"""common areas model

Revision ID: 1e369e4f68a7
Revises: 8bdcf554bd1f
Create Date: 2020-07-01 12:52:35.614228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e369e4f68a7"
down_revision = "8bdcf554bd1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "common_area",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("condominium", sa.Boolean(), nullable=True),
        sa.Column("purchase_year", sa.Date(), nullable=True),
        sa.Column("construction_year", sa.Date(), nullable=True),
        sa.Column("levels_nb", sa.Integer(), nullable=True),
        sa.Column("commentary", sa.String(length=800), nullable=True),
        sa.Column("accommodations_nb", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["core.project.id"],
            name=op.f("fk_common_area_project_id_project"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_common_area")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("common_area", schema="core")
    # ### end Alembic commands ###
