"""existing_solar_device

Revision ID: dded725aa928
Revises: b643ce814814
Create Date: 2020-11-17 16:53:56.608297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dded725aa928"
down_revision = "b643ce814814"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hot_water",
        "existing_solar_device",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Boolean(),
        existing_nullable=True,
        schema="core",
        postgresql_using="existing_solar_device::boolean",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hot_water",
        "existing_solar_device",
        existing_type=sa.Boolean(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
        schema="core",
    )
    # ### end Alembic commands ###
