"""add default and automatic MonitorField

Revision ID: 8c0af11ae386
Revises: 02972264ff4c
Create Date: 2020-08-26 15:08:46.383755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c0af11ae386"
down_revision = "02972264ff4c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitor_field",
        sa.Column("automatic", sa.Boolean(), nullable=True),
        schema="core",
    )
    op.add_column(
        "monitor_field",
        sa.Column("default", sa.Boolean(), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitor_field", "default", schema="core")
    op.drop_column("monitor_field", "automatic", schema="core")
    # ### end Alembic commands ###
