"""accommodation adaptation fields

Revision ID: c611cc7f5cdc
Revises: 636ab59b1524
Create Date: 2020-07-02 11:34:41.752280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c611cc7f5cdc"
down_revision = "636ab59b1524"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accommodation",
        sa.Column("GIR_coefficient", sa.Integer(), nullable=True),
        schema="core",
    )
    op.add_column(
        "accommodation",
        sa.Column(
            "disability_card", sa.Boolean(create_constraint=False), nullable=True
        ),
        schema="core",
    )
    op.add_column(
        "accommodation",
        sa.Column("has_AAH", sa.Boolean(create_constraint=False), nullable=True),
        schema="core",
    )
    op.add_column(
        "accommodation",
        sa.Column("has_APA", sa.Boolean(create_constraint=False), nullable=True),
        schema="core",
    )
    op.add_column(
        "accommodation",
        sa.Column("rate_adaptation", sa.Integer(), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accommodation", "rate_adaptation", schema="core")
    op.drop_column("accommodation", "has_APA", schema="core")
    op.drop_column("accommodation", "has_AAH", schema="core")
    op.drop_column("accommodation", "disability_card", schema="core")
    op.drop_column("accommodation", "GIR_coefficient", schema="core")
    # ### end Alembic commands ###
