"""add email model

Revision ID: 8b5fca25333a
Revises: eb869c77fa8a
Create Date: 2020-09-08 13:59:18.184313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8b5fca25333a"
down_revision = "eb869c77fa8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subject", sa.String(length=980), nullable=False),
        sa.Column(
            "to", postgresql.ARRAY(sa.String(length=255), dimensions=1), nullable=False
        ),
        sa.Column(
            "cc", postgresql.ARRAY(sa.String(length=255), dimensions=1), nullable=True
        ),
        sa.Column(
            "bcc", postgresql.ARRAY(sa.String(length=255), dimensions=1), nullable=True
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("sender_email", sa.String(length=255), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=True),
        sa.Column("sent_date", sa.DateTime(), nullable=True),
        sa.Column(
            "attachments",
            postgresql.ARRAY(sa.String(length=100), dimensions=1),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["core.project.id"],
            name=op.f("fk_email_project_id_project"),
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["core.user.id"], name=op.f("fk_email_sender_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email", schema="core")
    # ### end Alembic commands ###
