"""walls model

Revision ID: 77e9cd200f9a
Revises: bde507b73ff1
Create Date: 2020-10-28 18:27:12.417210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77e9cd200f9a"
down_revision = "bde507b73ff1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hot_water",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("boiler_type", sa.String(length=255), nullable=True),
        sa.Column("year_classic_accumulator", sa.String(length=255), nullable=True),
        sa.Column("has_light", sa.Boolean(), nullable=True),
        sa.Column("production_living_volume", sa.String(length=255), nullable=True),
        sa.Column("linked_rooms", sa.Boolean(), nullable=True),
        sa.Column("production_type", sa.String(length=255), nullable=True),
        sa.Column("water_tank_volume", sa.Integer(), nullable=True),
        sa.Column("renovated_production", sa.Boolean(), nullable=True),
        sa.Column("existing_solar_device", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["core.scenario.id"],
            name=op.f("fk_hot_water_scenario_id_scenario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hot_water")),
        schema="core",
    )
    op.create_table(
        "wall",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("wall_position", sa.String(length=255), nullable=True),
        sa.Column("insulated_heated_non_heated_wall", sa.Boolean(), nullable=True),
        sa.Column("insulated_non_heated_exterior_wall", sa.Boolean(), nullable=True),
        sa.Column("local_type", sa.String(length=255), nullable=True),
        sa.Column("known_U_value", sa.Boolean(), nullable=True),
        sa.Column("known_U", sa.Float(), nullable=True),
        sa.Column("wall_composition", sa.String(length=255), nullable=True),
        sa.Column("double_brick_with_air_gap", sa.Boolean(), nullable=True),
        sa.Column("insulated_wall", sa.Boolean(), nullable=True),
        sa.Column("R_value", sa.Float(), nullable=True),
        sa.Column("insulation_thickness", sa.Integer(), nullable=True),
        sa.Column("insulation_type", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["core.scenario.id"],
            name=op.f("fk_wall_scenario_id_scenario"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wall")),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wall", schema="core")
    op.drop_table("hot_water", schema="core")
    # ### end Alembic commands ###
