"""funders soft delete

Revision ID: a51d41774547
Revises: f3ce4872bc66
Create Date: 2020-07-10 13:13:16.761478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a51d41774547"
down_revision = "f3ce4872bc66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "funder", sa.Column("is_deleted", sa.Boolean(), nullable=True), schema="core"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("funder", "is_deleted", schema="core")
    # ### end Alembic commands ###
