"""allow to have multiple project ids in emails

Revision ID: e96e946952d8
Revises: 4d99630088e9
Create Date: 2020-09-09 08:14:15.735244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e96e946952d8"
down_revision = "4d99630088e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email",
        sa.Column(
            "project_ids", postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True
        ),
        schema="core",
    )
    op.drop_constraint(
        "fk_email_project_id_project", "email", schema="core", type_="foreignkey"
    )
    op.drop_column("email", "project_id", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email",
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="core",
    )
    op.create_foreign_key(
        "fk_email_project_id_project",
        "email",
        "project",
        ["project_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    op.drop_column("email", "project_ids", schema="core")
    # ### end Alembic commands ###
