"""documents evolution

Revision ID: a5881854fc52
Revises: 6a25c1265d86
Create Date: 2020-09-15 15:40:53.198124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5881854fc52"
down_revision = "6a25c1265d86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("document_id", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "document", sa.Column("project_id", sa.Integer(), nullable=True), schema="core"
    )
    op.add_column(
        "document",
        sa.Column("source", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "document",
        sa.Column("status", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "document",
        sa.Column("template_id", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "document", sa.Column("user_id", sa.Integer(), nullable=True), schema="core"
    )
    op.create_foreign_key(
        op.f("fk_document_user_id_user"),
        "document",
        "user",
        ["user_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    op.create_foreign_key(
        op.f("fk_document_project_id_project"),
        "document",
        "project",
        ["project_id"],
        ["id"],
        source_schema="core",
        referent_schema="core",
    )
    op.drop_column("document", "tag", schema="core")
    op.drop_column("document", "path", schema="core")
    op.drop_column("document", "type", schema="core")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document",
        sa.Column("type", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        schema="core",
    )
    op.add_column(
        "document",
        sa.Column("path", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        schema="core",
    )
    op.add_column(
        "document",
        sa.Column("tag", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        schema="core",
    )
    op.drop_constraint(
        op.f("fk_document_project_id_project"),
        "document",
        schema="core",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_document_user_id_user"), "document", schema="core", type_="foreignkey"
    )
    op.drop_column("document", "user_id", schema="core")
    op.drop_column("document", "template_id", schema="core")
    op.drop_column("document", "status", schema="core")
    op.drop_column("document", "source", schema="core")
    op.drop_column("document", "project_id", schema="core")
    op.drop_column("document", "document_id", schema="core")
    # ### end Alembic commands ###
