"""empty message

Revision ID: fb4f9f08e0c8
Revises: 2ccd2375d4ca
Create Date: 2021-11-25 09:26:47.839022

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fb4f9f08e0c8'
down_revision = '2ccd2375d4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('copro_id', sa.Integer(), nullable=False),
                    sa.Column('building_id', sa.Integer(), nullable=True),
                    sa.Column('lot_number', sa.Integer(), nullable=True),
                    sa.Column('type', sa.String(length=255), nullable=True),
                    sa.Column('owner_status', sa.String(length=255), nullable=True),
                    sa.Column('habitation_type', sa.String(length=255), nullable=True),
                    sa.Column('floor', sa.String(length=255), nullable=True),
                    sa.Column('door', sa.String(length=255), nullable=True),
                    sa.Column('surface', sa.Float(), nullable=True),
                    sa.Column('status_if_habitation', sa.String(length=255), nullable=True),
                    sa.Column('occupant_status', sa.String(length=255), nullable=True),
                    sa.Column('cave_surface', sa.Float(), nullable=True),
                    sa.Column('balcony_surface', sa.Float(), nullable=True),
                    sa.Column('unpaid_amount', sa.Float(), nullable=True),
                    sa.Column('unpaid_date', sa.Date(), nullable=True),
                    sa.Column('lease_type', sa.String(length=255), nullable=True),
                    sa.Column('rent_per_month', sa.Float(), nullable=True),
                    sa.Column('charges_per_month', sa.Float(), nullable=True),
                    sa.Column('intermediate_rent', sa.Boolean(), nullable=True),
                    sa.Column('convention_rent_type', sa.String(length=255), nullable=True),
                    sa.Column('dia', sa.Boolean(), nullable=True),
                    sa.Column('dia_price', sa.Float(), nullable=True),
                    sa.Column('dia_price_m2', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['building_id'], ['core.building.id'],
                                            name=op.f('fk_lot_building_id_building')),
                    sa.ForeignKeyConstraint(['copro_id'], ['core.copro.id'], name=op.f('fk_lot_copro_id_copro')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_lot')),
                    schema='core'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lot', schema='core')
    # ### end Alembic commands ###
