"""empty message

Revision ID: 5e7de5dfd5be
Revises: 03d418287dd0
Create Date: 2022-02-10 09:23:57.272739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e7de5dfd5be'
down_revision = '03d418287dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation', sa.Column('scenario_id', sa.Integer(), nullable=True), schema='core')
    op.create_foreign_key(op.f('fk_simulation_scenario_id_scenario'), 'simulation', 'scenario', ['scenario_id'], ['id'], source_schema='core', referent_schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_simulation_scenario_id_scenario'), 'simulation', schema='core', type_='foreignkey')
    op.drop_column('simulation', 'scenario_id', schema='core')
    # ### end Alembic commands ###
