"""empty message

Revision ID: a3af4bff64a5
Revises: fc7c92ced175
Create Date: 2021-11-09 16:02:09.531122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3af4bff64a5'
down_revision = 'fc7c92ced175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elect', sa.Column('name', sa.String(length=255), nullable=True), schema='core')
    op.drop_column('elect', 'first_name', schema='core')
    op.drop_column('elect', 'last_name', schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elect', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='core')
    op.add_column('elect', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='core')
    op.drop_column('elect', 'name', schema='core')
    # ### end Alembic commands ###
