"""empty message

Revision ID: 62a22dc1009e
Revises: d804b239d55d
Create Date: 2021-11-16 19:29:38.217535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a22dc1009e'
down_revision = 'd804b239d55d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copro', sa.Column('president_id', sa.Integer(), nullable=True), schema='core')
    op.create_foreign_key(op.f('fk_copro_president_id_president'), 'copro', 'president', ['president_id'], ['id'], source_schema='core', referent_schema='core')
    op.drop_constraint('fk_president_copro_id_copro', 'president', schema='core', type_='foreignkey')
    op.drop_column('president', 'copro_id', schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('president', sa.Column('copro_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='core')
    op.create_foreign_key('fk_president_copro_id_copro', 'president', 'copro', ['copro_id'], ['id'], source_schema='core', referent_schema='core')
    op.drop_constraint(op.f('fk_copro_president_id_president'), 'copro', schema='core', type_='foreignkey')
    op.drop_column('copro', 'president_id', schema='core')
    # ### end Alembic commands ###
