"""empty message

Revision ID: 19f2c1b8e1fd
Revises: 9d357548d1f8
Create Date: 2021-12-09 10:59:15.159125

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '19f2c1b8e1fd'
down_revision = '9d357548d1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thematique_entity',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('resource_type', sa.String(length=255), nullable=False),
                    sa.Column('resource_id', sa.Integer(), nullable=False),
                    sa.Column('document_id', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_thematique_entity')),
                    schema='core'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thematique_entity', schema='core')
    # ### end Alembic commands ###
