"""empty message

Revision ID: 6095508e6868
Revises: 58de9c6ce7c9
Create Date: 2021-07-09 15:26:24.994904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6095508e6868'
down_revision = '58de9c6ce7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('creator', sa.String(length=255), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mission', 'creator', schema='core')
    # ### end Alembic commands ###
