"""empty message

Revision ID: 46fe5d595ef1
Revises: fb4f9f08e0c8
Create Date: 2021-12-06 10:59:58.356947

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '46fe5d595ef1'
down_revision = 'fb4f9f08e0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('civility', sa.String(length=10), nullable=True),
                    sa.Column('status', sa.String(length=255), nullable=True),
                    sa.Column('first_name', sa.String(length=255), nullable=True),
                    sa.Column('last_name', sa.String(length=255), nullable=True),
                    sa.Column('company_name', sa.String(length=255), nullable=True),
                    sa.Column('email_address', sa.String(length=255), nullable=True),
                    sa.Column('antenna_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['antenna_id'], ['core.antenna.id'],
                                            name=op.f('fk_person_antenna_id_antenna')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_person')),
                    schema='core'
                    )
    op.create_table('lot_person',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('person_id', sa.Integer(), nullable=True),
                    sa.Column('lot_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['lot_id'], ['core.lot.id'], name=op.f('fk_lot_person_lot_id_lot')),
                    sa.ForeignKeyConstraint(['person_id'], ['core.person.id'],
                                            name=op.f('fk_lot_person_person_id_person')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_lot_person')),
                    schema='core'
                    )
    op.add_column('lot', sa.Column('owner_id', sa.Integer(), nullable=True), schema='core')
    op.create_foreign_key(op.f('fk_lot_owner_id_person'), 'lot', 'person', ['owner_id'], ['id'], source_schema='core',
                          referent_schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_lot_owner_id_person'), 'lot', schema='core', type_='foreignkey')
    op.drop_column('lot', 'owner_id', schema='core')
    op.drop_table('lot_person', schema='core')
    op.drop_table('person', schema='core')
    # ### end Alembic commands ###
