"""empty message

Revision ID: d8463c0cb6bd
Revises: 80aff1daca1e
Create Date: 2021-11-09 13:52:21.955064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8463c0cb6bd'
down_revision = '80aff1daca1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcontractor', sa.Column('active', sa.Boolean(), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcontractor', 'active', schema='core')
    # ### end Alembic commands ###
