"""empty message

Revision ID: fe580df46bd9
Revises: b6ea8de7b31d
Create Date: 2021-10-27 14:11:49.637394

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fe580df46bd9'
down_revision = 'b6ea8de7b31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'address',
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('full_address', sa.Text(), nullable=False),
        sa.Column('number', sa.String(length=50), nullable=False),
        sa.Column('street', sa.String(length=255), nullable=False),
        sa.Column('postal_code', sa.String(length=50), nullable=False),
        sa.Column('additional_info', sa.String(length=255), nullable=True),
        sa.Column('city', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_address')),
        schema='core'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address', schema='core')
    # ### end Alembic commands ###
