"""empty message

Revision ID: 9d357548d1f8
Revises: 0e7b99b4bb6a
Create Date: 2021-12-08 10:45:36.150913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d357548d1f8'
down_revision = '0e7b99b4bb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('is_physical_person', sa.Boolean(), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'is_physical_person', schema='core')
    # ### end Alembic commands ###
