"""empty message

Revision ID: 2ccd2375d4ca
Revises: a205658644af
Create Date: 2021-11-23 08:59:38.893428

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2ccd2375d4ca'
down_revision = 'a205658644af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('copro_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.Column('referents', sa.Text(), nullable=True),
                    sa.Column('construction_time', sa.String(length=255), nullable=True),
                    sa.Column('igh', sa.Boolean(), nullable=True),
                    sa.Column('r_plus', sa.String(length=255), nullable=True),
                    sa.Column('r_minus', sa.String(length=255), nullable=True),
                    sa.Column('erp', sa.Boolean(), nullable=True),
                    sa.Column('erp_category', sa.String(length=255), nullable=True),
                    sa.Column('last_security_commission_date', sa.Date(), nullable=True),
                    sa.Column('lodge', sa.Boolean(), nullable=True),
                    sa.Column('nb_habitations_rcp', sa.Integer(), nullable=True),
                    sa.Column('nb_habitations_noted', sa.Integer(), nullable=True),
                    sa.Column('total_surface', sa.Float(), nullable=True),
                    sa.Column('nb_annex_lots', sa.Integer(), nullable=True),
                    sa.Column('nb_aerial_parking_spaces', sa.Integer(), nullable=True),
                    sa.Column('nb_underground_parking_spaces', sa.Integer(), nullable=True),
                    sa.Column('access_type', sa.String(length=255), nullable=True),
                    sa.Column('access_code', sa.Text(), nullable=True),
                    sa.Column('access_type_cave', sa.String(length=255), nullable=True),
                    sa.Column('access_type_roof', sa.String(length=255), nullable=True),
                    sa.Column('lifts', sa.Integer(), nullable=True),
                    sa.Column('roof', sa.String(length=255), nullable=True),
                    sa.Column('vmc', sa.Boolean(), nullable=True),
                    sa.Column('collective_heater', sa.String(length=255), nullable=True),
                    sa.Column('ground_heating', sa.Boolean(), nullable=True),
                    sa.Column('individual_cold_water_counter', sa.Boolean(), nullable=True),
                    sa.Column('individual_ecs_counter', sa.Boolean(), nullable=True),
                    sa.Column('other_equipments', sa.Text(), nullable=True),
                    sa.Column('energy_diagnosis_date', sa.Date(), nullable=True),
                    sa.Column('initial_energy_label', sa.String(length=255), nullable=True),
                    sa.Column('initial_consumption', sa.Float(), nullable=True),
                    sa.Column('asbestos_diagnosis_date', sa.Date(), nullable=True),
                    sa.Column('asbestos_diagnosis_result', sa.String(length=255), nullable=True),
                    sa.Column('lead_diagnosis_date', sa.Date(), nullable=True),
                    sa.Column('security_commission_date', sa.Date(), nullable=True),
                    sa.Column('security_commission_result', sa.Text(), nullable=True),
                    sa.Column('other_technical_diagnosis', sa.Text(), nullable=True),
                    sa.Column('comment', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['address_id'], ['core.address.id'],
                                            name=op.f('fk_building_address_id_address')),
                    sa.ForeignKeyConstraint(['copro_id'], ['core.copro.id'], name=op.f('fk_building_copro_id_copro')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_building')),
                    schema='core'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('building', schema='core')
    # ### end Alembic commands ###
