"""empty message

Revision ID: b9f54bb64372
Revises: a50e2f29f878
Create Date: 2022-02-14 10:34:24.984271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9f54bb64372'
down_revision = 'a50e2f29f878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        "UPDATE core.enum "
        "SET name = 'LOCATAIRE' "
        "WHERE kind = 'ProjectRequesterType' AND name = 'TENANT'"
    )
    session.execute(
        "UPDATE core.requester "
        "SET type = 'LOCATAIRE' "
        "WHERE type IN ('Locataire', 'TENANT')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        "UPDATE core.enum "
        "SET name = 'TENANT' "
        "WHERE kind = 'ProjectRequesterType' AND name = 'LOCATAIRE'"
    )
    session.execute(
        "UPDATE core.requester "
        "SET type = 'TENANT' "
        "WHERE type IN ('Locataire', 'LOCATAIRE')"
    )
    # ### end Alembic commands ###
