"""empty message

Revision ID: 919538d32015
Revises: d29017cc78f8
Create Date: 2021-11-16 16:39:07.667907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919538d32015'
down_revision = 'd29017cc78f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copro', sa.Column('copro_type', sa.String(length=255), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copro', 'copro_type', schema='core')
    # ### end Alembic commands ###
