"""empty message

Revision ID: a205658644af
Revises: 62a22dc1009e
Create Date: 2021-11-22 09:22:13.902590

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a205658644af'
down_revision = '62a22dc1009e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moe',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('email_address', sa.String(length=255), nullable=True),
                    sa.Column('comment', sa.String(length=255), nullable=True),
                    sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['address_id'], ['core.address.id'],
                                            name=op.f('fk_moe_address_id_address')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_moe')),
                    schema='core'
                    )
    op.add_column('copro', sa.Column('moe_id', sa.Integer(), nullable=True), schema='core')
    op.create_foreign_key(op.f('fk_copro_moe_id_moe'), 'copro', 'moe', ['moe_id'], ['id'], source_schema='core',
                          referent_schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_copro_moe_id_moe'), 'copro', schema='core', type_='foreignkey')
    op.drop_column('copro', 'moe_id', schema='core')
    op.drop_table('moe', schema='core')
    # ### end Alembic commands ###
