"""empty message

Revision ID: 041f3d6ad25a
Revises: 82791b814266
Create Date: 2021-12-10 13:52:21.916337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041f3d6ad25a'
down_revision = '82791b814266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thematique_entity', schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thematique_entity',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('core.thematique_entity_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_thematique_entity'),
    schema='core'
    )
    # ### end Alembic commands ###
