"""empty message

Revision ID: 80aff1daca1e
Revises: 5fbf35376f18
Create Date: 2021-11-08 10:45:07.520372

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '80aff1daca1e'
down_revision = '5fbf35376f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcontractor',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('job', sa.String(length=255), nullable=True),
                    sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['address_id'], ['core.address.id'],
                                            name=op.f('fk_subcontractor_address_id_address')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_subcontractor')),
                    schema='core'
                    )
    op.create_table('mission_detail_subcontractor',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('subcontractor_id', sa.Integer(), nullable=True),
                    sa.Column('mission_detail_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['mission_detail_id'], ['core.mission_detail.id'], name=op.f(
                        'fk_mission_detail_subcontractor_mission_detail_id_mission_detail')),
                    sa.ForeignKeyConstraint(['subcontractor_id'], ['core.subcontractor.id'], name=op.f(
                        'fk_mission_detail_subcontractor_subcontractor_id_subcontractor')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_detail_subcontractor')),
                    schema='core'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mission_detail_subcontractor', schema='core')
    op.drop_table('subcontractor', schema='core')
    # ### end Alembic commands ###
