"""empty message

Revision ID: 0e7b99b4bb6a
Revises: 46fe5d595ef1
Create Date: 2021-12-06 16:32:32.810116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7b99b4bb6a'
down_revision = '46fe5d595ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('is_deleted', sa.Boolean(), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'is_deleted', schema='core')
    # ### end Alembic commands ###
