"""empty message

Revision ID: 5fbf35376f18
Revises: 5fcbe25b6734
Create Date: 2021-11-04 09:12:11.426344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbf35376f18'
down_revision = '5fcbe25b6734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_details_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('job', sa.String(length=255), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['core.address.id'], name=op.f('fk_partner_address_id_address')),
    sa.ForeignKeyConstraint(['mission_details_id'], ['core.mission_detail.id'], name=op.f('fk_partner_mission_details_id_mission_detail')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner', schema='core')
    # ### end Alembic commands ###
