"""empty message

Revision ID: 03d418287dd0
Revises: 6095508e6868
Create Date: 2022-02-15 14:45:26.401826

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '03d418287dd0'
down_revision = '6095508e6868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funder', sa.Column('position', sa.Integer(), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funder', 'position', schema='core')
    # ### end Alembic commands ###
