"""empty message

Revision ID: 82791b814266
Revises: 19f2c1b8e1fd
Create Date: 2021-12-09 11:04:08.262152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82791b814266'
down_revision = '19f2c1b8e1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thematique_mission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('thematique_name', sa.String(length=255), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['core.mission.id'], name=op.f('fk_thematique_mission_mission_id_mission')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thematique_mission')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thematique_mission', schema='core')
    # ### end Alembic commands ###
