"""empty message

Revision ID: 58de9c6ce7c9
Revises: 2f9a4c997400
Create Date: 2021-06-16 14:31:56.145068

"""
from alembic import op
from datetime import datetime
import sqlalchemy as sa
from sqlalchemy import MetaData, Table
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = '58de9c6ce7c9'
down_revision = '2f9a4c997400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('company_origin', sa.String(length=255), nullable=True), schema='core')

    meta = MetaData(bind=op.get_bind(), schema="core")
    meta.reflect(only=("enum",))
    enum_table = Table("enum", meta)
    
    additional_enums = {
        "QuoteCompanyOrigin": [
            "Commune",
            "EPCI",
            "Département",
            "Autre département",
            "Autre"
        ],
    }

    rows = []
    current_date = datetime.utcnow()
    for kind, items in additional_enums.items():
        for i, name in enumerate(items):
            rows.append(
                {
                    "name": name,
                    "kind": kind,
                    "display_order": i + 1,
                    "private": False,
                    "disabled": False,
                    "created_at": current_date,
                    "updated_at": current_date,
                }
            )

    op.bulk_insert(
        enum_table, rows,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'company_origin', schema='core')
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        "DELETE FROM core.enum WHERE kind = 'QuoteCompanyOrigin';"
    )
    # ### end Alembic commands ###
