"""empty message

Revision ID: 4ec050767555
Revises: df475db9c15a
Create Date: 2022-01-24 16:43:49.655696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec050767555'
down_revision = 'df475db9c15a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('combined_structure', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='core')
    op.alter_column('combined_structure', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('combined_structure', 'type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='core')
    op.alter_column('combined_structure', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='core')
    # ### end Alembic commands ###
