"""empty message

Revision ID: d3ac5f2e9fa7
Revises: eee6ff882803
Create Date: 2022-09-21 16:38:48.763950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ac5f2e9fa7'
down_revision = 'eee6ff882803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_detail', sa.Column('market_notification_date', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('market_price_revision', sa.Boolean(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('invoicing_terms_specifics', sa.String(), nullable=True), schema='core')
    op.drop_column('mission_detail', 'os_signing_date', schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_detail', sa.Column('os_signing_date', sa.DATE(), autoincrement=False, nullable=True), schema='core')
    op.drop_column('mission_detail', 'invoicing_terms_specifics', schema='core')
    op.drop_column('mission_detail', 'market_price_revision', schema='core')
    op.drop_column('mission_detail', 'market_notification_date', schema='core')
    # ### end Alembic commands ###
