"""empty message

Revision ID: 1a8a8d1d46e7
Revises: fd2159c85523
Create Date: 2022-01-07 10:20:18.669882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8a8d1d46e7'
down_revision = 'fd2159c85523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cle_repartition', 'is_deleted', schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cle_repartition', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='core')
    # ### end Alembic commands ###
