"""empty message

Revision ID: 786cf16624b0
Revises: 5a07effd417d
Create Date: 2022-02-25 14:33:49.160566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786cf16624b0'
down_revision = '5a07effd417d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('import_sheet_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('log_sheet_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['core.mission.id'], name=op.f('fk_imports_mission_id_mission')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imports')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imports', schema='core')
    # ### end Alembic commands ###
