"""empty message

Revision ID: 7460f8230870
Revises: 7164f8d80992
Create Date: 2022-06-03 16:23:28.646089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7460f8230870'
down_revision = '7164f8d80992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_detail', sa.Column('financial_device_used', sa.Boolean(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('mandate_account_type', sa.String(length=255), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('organization_funds_provider', sa.String(length=255), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('bank_account_name', sa.String(length=255), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('bank_name', sa.String(length=255), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('agreement_signature_date', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('amendment_signature_date', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('convention_number', sa.String(length=255), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('initiale_envelop', sa.Integer(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('complementary_envelop', sa.Integer(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('internal_audit_date', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('external_audit_date', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('funds_return_date', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('amount_returned', sa.Integer(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('closing_date', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('transfer_circuit_validation', sa.String(length=500), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('operating_details', sa.String(length=500), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('smq_meeting_progress_1', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('smq_meeting_progress_2', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('smq_meeting_progress_3', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('smq_meeting_progress_4', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('smq_meeting_progress_5', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('smq_meeting_cloture', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('smq_internal_audit_date', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('smq_external_audit_date', sa.Date(), nullable=True), schema='core')
    op.add_column('mission_detail', sa.Column('sqm_commentary', sa.String(length=500), nullable=True), schema='core')
    op.drop_column('mission_detail', 'smq_previous_meeting', schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_detail', sa.Column('smq_previous_meeting', sa.DATE(), autoincrement=False, nullable=True), schema='core')
    op.drop_column('mission_detail', 'sqm_commentary', schema='core')
    op.drop_column('mission_detail', 'smq_external_audit_date', schema='core')
    op.drop_column('mission_detail', 'smq_internal_audit_date', schema='core')
    op.drop_column('mission_detail', 'smq_meeting_cloture', schema='core')
    op.drop_column('mission_detail', 'smq_meeting_progress_5', schema='core')
    op.drop_column('mission_detail', 'smq_meeting_progress_4', schema='core')
    op.drop_column('mission_detail', 'smq_meeting_progress_3', schema='core')
    op.drop_column('mission_detail', 'smq_meeting_progress_2', schema='core')
    op.drop_column('mission_detail', 'smq_meeting_progress_1', schema='core')
    op.drop_column('mission_detail', 'operating_details', schema='core')
    op.drop_column('mission_detail', 'transfer_circuit_validation', schema='core')
    op.drop_column('mission_detail', 'closing_date', schema='core')
    op.drop_column('mission_detail', 'amount_returned', schema='core')
    op.drop_column('mission_detail', 'funds_return_date', schema='core')
    op.drop_column('mission_detail', 'external_audit_date', schema='core')
    op.drop_column('mission_detail', 'internal_audit_date', schema='core')
    op.drop_column('mission_detail', 'complementary_envelop', schema='core')
    op.drop_column('mission_detail', 'initiale_envelop', schema='core')
    op.drop_column('mission_detail', 'convention_number', schema='core')
    op.drop_column('mission_detail', 'amendment_signature_date', schema='core')
    op.drop_column('mission_detail', 'agreement_signature_date', schema='core')
    op.drop_column('mission_detail', 'bank_name', schema='core')
    op.drop_column('mission_detail', 'bank_account_name', schema='core')
    op.drop_column('mission_detail', 'organization_funds_provider', schema='core')
    op.drop_column('mission_detail', 'mandate_account_type', schema='core')
    op.drop_column('mission_detail', 'financial_device_used', schema='core')
    # ### end Alembic commands ###
