"""empty message

Revision ID: fd2159c85523
Revises: fed4e3f0cdbc
Create Date: 2022-01-07 10:03:06.419096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2159c85523'
down_revision = 'fed4e3f0cdbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cle_repartition',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('copro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['copro_id'], ['core.copro.id'], name=op.f('fk_cle_repartition_copro_id_copro')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cle_repartition')),
    schema='core'
    )
    op.create_table('lot_cle_repartition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('cle_repartition_id', sa.Integer(), nullable=False),
    sa.Column('tantieme', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cle_repartition_id'], ['core.cle_repartition.id'], name=op.f('fk_lot_cle_repartition_cle_repartition_id_cle_repartition')),
    sa.ForeignKeyConstraint(['lot_id'], ['core.lot.id'], name=op.f('fk_lot_cle_repartition_lot_id_lot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lot_cle_repartition')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lot_cle_repartition', schema='core')
    op.drop_table('cle_repartition', schema='core')
    # ### end Alembic commands ###
