"""empty message

Revision ID: fa21a36033f8
Revises: d24c1f1d999b
Create Date: 2022-04-19 16:23:24.869548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa21a36033f8'
down_revision = 'd24c1f1d999b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('export_sheet_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('export_type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['core.user.id'], name=op.f('fk_exports_author_id_user')),
    sa.ForeignKeyConstraint(['mission_id'], ['core.mission.id'], name=op.f('fk_exports_mission_id_mission')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exports')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exports', schema='core')
    # ### end Alembic commands ###
