"""empty message

Revision ID: 00a01f83596d
Revises: 041f3d6ad25a
Create Date: 2022-01-05 14:51:27.850214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a01f83596d'
down_revision = '041f3d6ad25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('reminder_date', sa.DateTime(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['core.user.id'], name=op.f('fk_task_assignee_id_user')),
    sa.ForeignKeyConstraint(['author_id'], ['core.user.id'], name=op.f('fk_task_author_id_user')),
    sa.ForeignKeyConstraint(['mission_id'], ['core.mission.id'], name=op.f('fk_task_mission_id_mission')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task', schema='core')
    # ### end Alembic commands ###
