"""empty message

Revision ID: f07ff0297808
Revises: 6d53e4f36348
Create Date: 2022-01-05 16:32:45.950018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07ff0297808'
down_revision = '6d53e4f36348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('step_id', sa.String(length=255), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'step_id', schema='core')
    # ### end Alembic commands ###
