"""empty message

Revision ID: d5665f887553
Revises: b054eaa1d606
Create Date: 2022-05-23 10:43:23.733308

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd5665f887553'
down_revision = 'b054eaa1d606'
branch_labels = None
depends_on = None

enums = {
    "HeaterBillingType": [
        "Collectif",
        "Individuel"
    ]
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    now = datetime.today().strftime("%Y-%m-%d %H:%M:%S.%f")
    # Add not existing enums
    for (kind, values) in enums.items():
        for value in values:
            session.execute(
                "INSERT INTO core.enum (created_at, updated_at, kind, name, display_order, disabled, private) VALUES "
                f"('{now}', '{now}', '{kind}', '{value}', NULL, false, false);"
            )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    # Remove not existing enums
    for (kind, values) in enums.items():
        for value in values:
            session.execute(
                f"DELETE FROM core.enum WHERE kind = '{kind}' AND name = '{value}';"
            )
    # ### end Alembic commands ###
