"""empty message

Revision ID: 080cb19518ad
Revises: 2cf385fcbfc3
Create Date: 2022-04-25 14:24:00.585096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080cb19518ad'
down_revision = '2cf385fcbfc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historic', sa.Column('step_name', sa.String(), nullable=False), schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historic', 'step_name', schema='core')
    # ### end Alembic commands ###
