"""empty message

Revision ID: 916eac5ed2e5
Revises: 544adbbcc18e
Create Date: 2022-06-08 16:18:48.731674

"""
from datetime import datetime
from alembic import op
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = '916eac5ed2e5'
down_revision = '544adbbcc18e'
branch_labels = None
depends_on = None

enums = {
    "FinancialDeviceType": [
       "FIH",
       "FIQ",
       "Compte d''avance",
       "FAP",
       "Autre",
    ]
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    now = datetime.today().strftime("%Y-%m-%d %H:%M:%S.%f")
    # Add not existing enums
    for (kind, values) in enums.items():
        for value in values:
            session.execute(
                "INSERT INTO core.enum (created_at, updated_at, kind, name, display_order, disabled, private) VALUES "
                f"('{now}', '{now}', '{kind}', '{value}', NULL, false, false);"
            )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    # Remove not existing enums
    for (kind, values) in enums.items():
        for value in values:
            session.execute(
                f"DELETE FROM core.enum WHERE kind = '{kind}' AND name = '{value}';"
            )
    # ### end Alembic commands ###
