"""empty message

Revision ID: fed4e3f0cdbc
Revises: f07ff0297808
Create Date: 2022-01-05 18:40:07.391792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed4e3f0cdbc'
down_revision = 'f07ff0297808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('version_id', sa.String(length=255), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'version_id', schema='core')
    # ### end Alembic commands ###
