"""empty message

Revision ID: 07774bccc88f
Revises: 3e8709f3af6d
Create Date: 2022-01-12 15:16:12.901950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = '07774bccc88f'
down_revision = '3e8709f3af6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('copro', 'copro_registry_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute('ALTER TABLE core.copro ALTER COLUMN copro_registry_number TYPE integer USING (copro_registry_number::integer)')
    # ### end Alembic commands ###
