"""empty message

Revision ID: c4336a4a2be3
Revises: 47b373758e63
Create Date: 2022-03-04 10:05:35.829189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4336a4a2be3'
down_revision = '47b373758e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('import_type', sa.String(length=255), nullable=True), schema='core')
    op.drop_column('imports', 'label', schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='core')
    op.drop_column('imports', 'import_type', schema='core')
    # ### end Alembic commands ###
