"""empty message

Revision ID: fd623e7bb59d
Revises: e4a2045a881f
Create Date: 2022-02-23 13:58:16.032629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd623e7bb59d'
down_revision = 'e4a2045a881f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('address_id', sa.Integer(), nullable=True), schema='core')
    op.create_foreign_key(op.f('fk_person_address_id_address'), 'person', 'address', ['address_id'], ['id'], source_schema='core', referent_schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_person_address_id_address'), 'person', schema='core', type_='foreignkey')
    op.drop_column('person', 'address_id', schema='core')
    # ### end Alembic commands ###
