"""empty message

Revision ID: d136e7d303e1
Revises: d4981678234b
Create Date: 2022-03-22 15:05:31.234990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd136e7d303e1'
down_revision = 'd4981678234b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copro', 'admin_type', schema='core')
    op.alter_column('lot', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lot', 'building_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='core')
    op.add_column('copro', sa.Column('admin_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='core')
    # ### end Alembic commands ###
