"""empty message

Revision ID: eee6ff882803
Revises: cb1820d0b6f8
Create Date: 2022-09-14 16:59:25.083834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eee6ff882803"
down_revision = "cb1820d0b6f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "copro",
        sa.Column(
            "sdv2_environement_urbain_folder_id", sa.String(length=255), nullable=True
        ),
        schema="core",
    )
    op.add_column(
        "copro",
        sa.Column(
            "sdv2_situation_juridique_folder_id", sa.String(length=255), nullable=True
        ),
        schema="core",
    )
    op.add_column(
        "copro",
        sa.Column("sdv2_occupation_folder_id", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "copro",
        sa.Column("sdv2_gestion_folder_id", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "copro",
        sa.Column("sdv2_charges_folder_id", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "copro",
        sa.Column("sdv2_impayes_folder_id", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "copro",
        sa.Column("sdv2_equipements_folder_id", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "copro",
        sa.Column(
            "sdv2_suivi_financement_pc_folder_id", sa.String(length=255), nullable=True
        ),
        schema="core",
    )
    op.add_column(
        "copro",
        sa.Column(
            "sdv2_suivi_financement_pp_folder_id", sa.String(length=255), nullable=True
        ),
        schema="core",
    )
    op.add_column(
        "copro",
        sa.Column(
            "sdv2_positionnement_folder_id", sa.String(length=255), nullable=True
        ),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("copro", "sdv2_positionnement_folder_id", schema="core")
    op.drop_column("copro", "sdv2_suivi_financement_pp_folder_id", schema="core")
    op.drop_column("copro", "sdv2_suivi_financement_pc_folder_id", schema="core")
    op.drop_column("copro", "sdv2_equipements_folder_id", schema="core")
    op.drop_column("copro", "sdv2_impayes_folder_id", schema="core")
    op.drop_column("copro", "sdv2_charges_folder_id", schema="core")
    op.drop_column("copro", "sdv2_gestion_folder_id", schema="core")
    op.drop_column("copro", "sdv2_occupation_folder_id", schema="core")
    op.drop_column("copro", "sdv2_situation_juridique_folder_id", schema="core")
    op.drop_column("copro", "sdv2_environement_urbain_folder_id", schema="core")
    # ### end Alembic commands ###
