"""empty message

Revision ID: cd1b8543d53a
Revises: d136e7d303e1
Create Date: 2022-03-22 16:10:41.069024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1b8543d53a'
down_revision = 'd136e7d303e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historic',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thematique_id', sa.String(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=False),
    sa.Column('new_value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historic')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historic', schema='core')
    # ### end Alembic commands ###
