"""empty message

Revision ID: 0d4573ab9284
Revises: 01a6fe37c511
Create Date: 2022-05-04 14:00:00.710460

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = '0d4573ab9284'
down_revision = '01a6fe37c511'
branch_labels = None
depends_on = None


existing_enums = {
    "Job": [
        "Etudes et conseil",
        "Habitat ancien",
        "Copropriétés",
        "Rénovation énergétique"
    ],
    "OperationalPlan": [
        "VOC",
        "Etude préalable",
        "POPAC",
        "ETEHC",
        "Diffus rénovation énergétique",
        "USR",
        "PIG rénovation énergétique",
        "PIG autre thématique",
        "Etude pré-opérationnelle",
        "OPAH volet copropriétés",
        "OPAH-CD",
        "Plan de sauvegarde",
        "ORCOD",
        "Autres dispositifs",
        "Autres études"
    ]
  
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    now = datetime.today().strftime("%Y-%m-%d %H:%M:%S.%f")
    # Merge existing enums
    for (kind, values) in existing_enums.items():
        for value in values:
            # Check if name already exists
            res = session.execute(f"SELECT name FROM core.enum WHERE kind = '{kind}' AND name = '{value}'")
            found = False
            for _ in res:
                found = True
            if not found:
                # Add it if not
                session.execute(
                    "INSERT INTO core.enum (created_at, updated_at, kind, name, display_order, disabled, private) VALUES "
                    f"('{now}', '{now}', '{kind}', '{value}', NULL, false, false)"
                )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
