"""empty message

Revision ID: 27454aa2af37
Revises: 7ea21155eb8b
Create Date: 2022-05-10 16:31:06.327728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27454aa2af37'
down_revision = '7ea21155eb8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('linked_mission', sa.JSON(), nullable=False), schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'linked_mission', schema='core')
    # ### end Alembic commands ###
