"""empty message

Revision ID: b054eaa1d606
Revises: 18f0c5cfdcf7
Create Date: 2022-05-18 10:39:51.527090

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'b054eaa1d606'
down_revision = '18f0c5cfdcf7'
branch_labels = None
depends_on = None

enums = {
    "NatureSuivi": [
        "Orientation",
        "Info droits / devoirs",
        "Info risque plomb",
        "Sensibilisation bons usages du logement",
        "Aide ouverture de droits",
        "Aide apurement de dettes",
        "Aide recherche solution financement quote-part travaux",
        "Aide recherche hébergement",
        "Appui démarches de relogement",
        "Médiation loc/proprio"
    ],
    "FSLType": [
        "FSL Accès",
        "FSL Maintien"
    ],
    "AccompaniementClosing": [
        "Motif de clôture",
        "Refus de l''accompagnement",
        "Aucun contact établi",
        "Vente",
        "Déménagement",
        "Changement de statut de propriété",
        "Décès",
        "Fin du dispositif public",
        "NR",
        "Autre"
    ]
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    now = datetime.today().strftime("%Y-%m-%d %H:%M:%S.%f")
    # Add not existing enums
    for (kind, values) in enums.items():
        for value in values:
            session.execute(
                "INSERT INTO core.enum (created_at, updated_at, kind, name, display_order, disabled, private) VALUES "
                f"('{now}', '{now}', '{kind}', '{value}', NULL, false, false);"
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    # Remove not existing enums
    for (kind, values) in enums.items():
        for value in values:
            session.execute(
                f"DELETE FROM core.enum WHERE kind = '{kind}' AND name = '{value}';"
            )
    # ### end Alembic commands ###
