"""empty message

Revision ID: 83f2f6a8ea59
Revises: c4336a4a2be3
Create Date: 2022-03-04 17:40:18.755230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f2f6a8ea59'
down_revision = 'c4336a4a2be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('author_id', sa.Integer(), nullable=False), schema='core')
    op.create_foreign_key(op.f('fk_imports_author_id_user'), 'imports', 'user', ['author_id'], ['id'], source_schema='core', referent_schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_imports_author_id_user'), 'imports', schema='core', type_='foreignkey')
    op.drop_column('imports', 'author_id', schema='core')
    # ### end Alembic commands ###
