"""empty message

Revision ID: 4c2d4653964f
Revises: d3ac5f2e9fa7
Create Date: 2022-09-27 16:19:27.112679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4c2d4653964f"
down_revision = "d3ac5f2e9fa7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "copro",
        sa.Column("sdv2_root_thematic_folder_id", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("sdv2_donnees_sortie_folder", sa.String(length=255), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mission", "sdv2_donnees_sortie_folder", schema="core")
    op.drop_column("copro", "sdv2_root_thematic_folder_id", schema="core")
    # ### end Alembic commands ###
