"""empty message

Revision ID: e4a2045a881f
Revises: b9f54bb64372
Create Date: 2022-02-22 09:44:08.783336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = 'e4a2045a881f'
down_revision = 'b9f54bb64372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_type', sa.String(length=5), default="TASK", nullable=True), schema='core')
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        "UPDATE core.task "
        "SET task_type = 'TASK' "
        "WHERE task_type is NULL"
    )
    op.alter_column('task', 'task_type',
                    existing_type=sa.VARCHAR(length=5),
                    nullable=False,
                    schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'task_type', schema='core')
    # ### end Alembic commands ###
