"""empty message

Revision ID: cb1820d0b6f8
Revises: 54698e2aec34
Create Date: 2022-09-14 12:06:34.796344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cb1820d0b6f8"
down_revision = "54698e2aec34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mission",
        sa.Column("sdv2_operationel_drive", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("sdv2_operationel_folder", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("sdv2_administratif_drive", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("sdv2_administratif_folder", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("sdv2_suivi_animation_folder", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("sdv2_outils_animation_folder", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("sdv2_equipes_locales_folder", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("sdv2_bdd_folder", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("sdv2_exports_folder", sa.String(length=255), nullable=True),
        schema="core",
    )
    op.add_column(
        "mission",
        sa.Column("sdv2_imports_folder", sa.String(length=255), nullable=True),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mission", "sdv2_imports_folder", schema="core")
    op.drop_column("mission", "sdv2_exports_folder", schema="core")
    op.drop_column("mission", "sdv2_bdd_folder", schema="core")
    op.drop_column("mission", "sdv2_equipes_locales_folder", schema="core")
    op.drop_column("mission", "sdv2_outils_animation_folder", schema="core")
    op.drop_column("mission", "sdv2_suivi_animation_folder", schema="core")
    op.drop_column("mission", "sdv2_administratif_folder", schema="core")
    op.drop_column("mission", "sdv2_administratif_drive", schema="core")
    op.drop_column("mission", "sdv2_operationel_folder", schema="core")
    op.drop_column("mission", "sdv2_operationel_drive", schema="core")
    # ### end Alembic commands ###
