"""empty message

Revision ID: d4981678234b
Revises: b16e2c5183aa
Create Date: 2022-03-22 09:15:29.905150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4981678234b'
down_revision = 'b16e2c5183aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    session.execute(
        "UPDATE core.requester "
        "SET type = 'SDC' "
        "WHERE type LIKE 'SDC%'"
    )
    # ### end Alembic commands ###


def downgrade():
    pass