"""empty message

Revision ID: df475db9c15a
Revises: 0327d51d579b
Create Date: 2022-01-24 15:53:23.397736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df475db9c15a'
down_revision = '0327d51d579b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combined_structure',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('mission_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('type', sa.String(length=255), nullable=False),
                    sa.Column('currently_working_on',
                              sa.Boolean(), nullable=True),
                    sa.Column('nb_lots', sa.Integer(), nullable=True),
                    sa.Column('nb_copros', sa.Integer(), nullable=True),
                    sa.Column('creation_year', sa.Integer(), nullable=True),
                    sa.Column('other_objects_linked',
                              sa.Boolean(), nullable=True),
                    sa.Column('other_objects_linked_details',
                              sa.Text(), nullable=True),
                    sa.Column('president_id', sa.Integer(), nullable=False),
                    sa.Column('members_cs', sa.Text(), nullable=True),
                    sa.Column('annual_budget', sa.Float(), nullable=True),
                    sa.Column('last_general_assemblee_date',
                              sa.Date(), nullable=True),
                    sa.Column('account_closing_date',
                              sa.String(), nullable=True),
                    sa.Column('main_member_exists',
                              sa.Boolean(), nullable=True),
                    sa.Column('main_member', sa.Text(), nullable=True),
                    sa.Column('rules_exists', sa.Boolean(), nullable=True),
                    sa.Column('total_tantieme',
                              sa.BigInteger(), nullable=True),
                    sa.Column('green_spaces', sa.Boolean(), nullable=True),
                    sa.Column('heater', sa.Boolean(), nullable=True),
                    sa.Column('aerial_parking', sa.Boolean(), nullable=True),
                    sa.Column('underground_parking',
                              sa.Boolean(), nullable=True),
                    sa.Column('cctv', sa.Boolean(), nullable=True),
                    sa.Column('other_equipments', sa.Boolean(), nullable=True),
                    sa.Column('other_equipments_details',
                              sa.Text(), nullable=True),
                    sa.Column('contract_syndic', sa.Boolean(), nullable=True),
                    sa.Column('contract_syndic_date',
                              sa.String(), nullable=True),
                    sa.Column('contract_green_spaces',
                              sa.Boolean(), nullable=True),
                    sa.Column('contract_green_spaces_date',
                              sa.String(), nullable=True),
                    sa.Column('contract_heater', sa.Boolean(), nullable=True),
                    sa.Column('contract_heater_date',
                              sa.String(), nullable=True),
                    sa.Column('contract_trash_room',
                              sa.Boolean(), nullable=True),
                    sa.Column('contract_trash_room_date',
                              sa.String(), nullable=True),
                    sa.Column('contract_trash_management',
                              sa.Boolean(), nullable=True),
                    sa.Column('contract_trash_management_date',
                              sa.String(), nullable=True),
                    sa.Column('contract_lodge', sa.Boolean(), nullable=True),
                    sa.Column('contract_lodge_date',
                              sa.String(), nullable=True),
                    sa.Column('contract_aerial_parking',
                              sa.Boolean(), nullable=True),
                    sa.Column('contract_aerial_parking_date',
                              sa.String(), nullable=True),
                    sa.Column('contract_underground_parking',
                              sa.Boolean(), nullable=True),
                    sa.Column('contract_underground_parking_date',
                              sa.String(), nullable=True),
                    sa.Column('contract_cctv', sa.Boolean(), nullable=True),
                    sa.Column('contract_cctv_date',
                              sa.String(), nullable=True),
                    sa.Column('other_technical_equipments',
                              sa.Boolean(), nullable=True),
                    sa.Column('comment', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['mission_id'], ['core.mission.id'], name=op.f(
                        'fk_combined_structure_mission_id_mission')),
                    sa.ForeignKeyConstraint(['president_id'], ['core.president.id'], name=op.f(
                        'fk_combined_structure_president_id_president')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_combined_structure')),
                    schema='core'
                    )
    op.add_column('copro', sa.Column(
        'cs_id', sa.Integer(), nullable=True), schema='core')
    op.create_foreign_key(op.f('fk_copro_cs_id_combined_structure'), 'copro', 'combined_structure', [
                          'cs_id'], ['id'], source_schema='core', referent_schema='core')
    op.add_column('president', sa.Column('election_date',
                  sa.Date(), nullable=True), schema='core')
    op.add_column('syndic', sa.Column(
        'cs_id', sa.Integer(), nullable=True), schema='core')
    op.add_column('syndic', sa.Column('contract_date',
                  sa.Date(), nullable=True), schema='core')
    op.alter_column('syndic', 'copro_id',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    schema='core')
    op.create_foreign_key(op.f('fk_syndic_cs_id_combined_structure'), 'syndic', 'combined_structure', [
                          'cs_id'], ['id'], source_schema='core', referent_schema='core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_syndic_cs_id_combined_structure'),
                       'syndic', schema='core', type_='foreignkey')
    op.alter_column('syndic', 'copro_id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    schema='core')
    op.drop_column('syndic', 'contract_date', schema='core')
    op.drop_column('syndic', 'cs_id', schema='core')
    op.drop_column('president', 'election_date', schema='core')
    op.drop_constraint(op.f('fk_copro_cs_id_combined_structure'),
                       'copro', schema='core', type_='foreignkey')
    op.drop_column('copro', 'cs_id', schema='core')
    op.drop_table('combined_structure', schema='core')
    # ### end Alembic commands ###
