THEMATICS = [
    "ENVIRONNEMENT_CADRE_VIE",
    "SITUATION_JURIDIQUE_FONCIERE",
    "OCCUPATION_SOCIALE",
    "GESTION_FONCTIONNEMENT",
    "CHARGES",
    "IMPAYES",
    "EQUIPEMENT_BATI",
    "SUIVI_FINANCEMENT",
    "POSITIONNEMENT_IMMOBILIER"
]